[package]
name = "axton-sim"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axton-protocols = { path = "../protocols" }
axton-core = { path = "../core" }
axton-client = { path = "../client" }
axton-sqlite = { path = "../sqlite" }
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
axton-server = { path = "../server" }
axton-binding = { path = "../../bindings/common" }
