// Generated by axton. Do not edit.
import { Client, type ClientSyncState, type Connection, type ConnectionOptions, type PrerequisiteHandler, type QuerySpec, type RebuildReport, type RecordValue, type ServerOptions, type StoreHook, type Subscription } from "../../packages/client-js/index.mts";
export { AdmissionRefused, CallError, PrerequisiteRetry, type Call, type CallOptions, type CallOutcome, type CallStatus, type OnceOptions, type PrerequisiteHandler, type ServerOptions, type Connection, type ConnectionOptions, type BootstrapPhase, type BootstrapStatus, type Subscription, type SubscriptionStatus } from "../../packages/client-js/index.mts";
import { schema, liveModels, makeMutations, makeQueries, GeneratedTransaction, ApplicationTransaction, type LiveModels, type StoreHooks, type StoreChange } from "./generated.ts";
import { decodeTodo, decodeTodoIdentity, type Todo, type TodoIdentity } from "./generated.ts";
import { decodeNote, decodeNoteIdentity, type Note, type NoteIdentity } from "./generated.ts";
import { decodeComposition, decodeCompositionIdentity, type Composition, type CompositionIdentity } from "./generated.ts";
import { decodeEntry, decodeEntryIdentity, type Entry, type EntryIdentity } from "./generated.ts";
import { decodeMedia, decodeMediaIdentity, type Media, type MediaIdentity } from "./generated.ts";
import { decodePlacement, decodePlacementIdentity, type Placement, type PlacementIdentity } from "./generated.ts";
import { fetchModels, type FetchModels } from "./generated.ts";
export * from "./generated.ts";
/** The Scopes this client follows; `subscribe` answers with the runtime's handle for one persistent registration. */
export class Scopes { readonly #client: Client;
 constructor(client: Client) { this.#client = client; }
 subscribe(scope: string): Promise<Subscription> { return this.#client.subscribeScope(scope); }
}
/** The retained `channels` spelling of the same registrations; `scopes` is the current one. */
export class Channels { readonly #client: Client;
 constructor(client: Client) { this.#client = client; }
 subscribe(channel: string): Promise<Subscription> { return this.#client.subscribe(channel); }
 unsubscribe(channel: string): Promise<void> { return this.#client.unsubscribe(channel); }
}
export class GeneratedClient {
 /** @internal The runtime handle; application code uses the members below. */
 readonly client: Client;
 connection: Connection | undefined;
 readonly models: LiveModels;
 /** Durable by default: `await` resolves after local acceptance with a `Call`; `mutations.call` waits for the backend outcome. */
 readonly mutations: ReturnType<typeof makeMutations>;
 /** Direct by default: `await` resolves with the backend result; `queries.enqueue` accepts durably with a `Call`. */
 readonly queries: ReturnType<typeof makeQueries>;
 readonly scopes: Scopes;
 readonly channels: Channels;
 /** One-shot remote reads of one Model by identity through its Loader; stored locally unless `store: false`. */
 readonly fetch: FetchModels;
 private constructor(client: Client, connection: Connection | undefined) { this.client = client; this.connection = connection; this.models = liveModels(client); this.mutations = makeMutations(client); this.queries = makeQueries(client); this.scopes = new Scopes(client); this.channels = new Channels(client); this.fetch = fetchModels(client); }
 /** Opens the local database at `path`. With a server, the connection starts immediately and retries on its own. */
 static async open(options: { path: string; server?: ServerOptions; connection?: ConnectionOptions; migration?: { defaults?: RecordValue; replayPull?: boolean }; discardPending?: boolean; onStore?: StoreHooks; prerequisites?: Record<string, PrerequisiteHandler> }): Promise<GeneratedClient> {
  const rawHooks: Record<string, StoreHook> = {};
  const todoHook = options.onStore?.todo;
  if (todoHook) rawHooks['Todo'] = (tx, changes) => todoHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<TodoIdentity,Todo> => change.kind === 'upsert' ? {kind:'upsert',identity:decodeTodoIdentity(change.identity),row:decodeTodo(change.row)} : {kind:'delete',identity:decodeTodoIdentity(change.identity)}));
  const noteHook = options.onStore?.note;
  if (noteHook) rawHooks['Note'] = (tx, changes) => noteHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<NoteIdentity,Note> => change.kind === 'upsert' ? {kind:'upsert',identity:decodeNoteIdentity(change.identity),row:decodeNote(change.row)} : {kind:'delete',identity:decodeNoteIdentity(change.identity)}));
  const compositionHook = options.onStore?.composition;
  if (compositionHook) rawHooks['Composition'] = (tx, changes) => compositionHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<CompositionIdentity,Composition> => change.kind === 'upsert' ? {kind:'upsert',identity:decodeCompositionIdentity(change.identity),row:decodeComposition(change.row)} : {kind:'delete',identity:decodeCompositionIdentity(change.identity)}));
  const entryHook = options.onStore?.entry;
  if (entryHook) rawHooks['Entry'] = (tx, changes) => entryHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<EntryIdentity,Entry> => change.kind === 'upsert' ? {kind:'upsert',identity:decodeEntryIdentity(change.identity),row:decodeEntry(change.row)} : {kind:'delete',identity:decodeEntryIdentity(change.identity)}));
  const mediaHook = options.onStore?.media;
  if (mediaHook) rawHooks['Media'] = (tx, changes) => mediaHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<MediaIdentity,Media> => change.kind === 'upsert' ? {kind:'upsert',identity:decodeMediaIdentity(change.identity),row:decodeMedia(change.row)} : {kind:'delete',identity:decodeMediaIdentity(change.identity)}));
  const placementHook = options.onStore?.placement;
  if (placementHook) rawHooks['Placement'] = (tx, changes) => placementHook(new GeneratedTransaction(tx), changes.map((change):StoreChange<PlacementIdentity,Placement> => change.kind === 'upsert' ? {kind:'upsert',identity:decodePlacementIdentity(change.identity),row:decodePlacement(change.row)} : {kind:'delete',identity:decodePlacementIdentity(change.identity)}));
  if ("transport" in options || "live" in options) throw Error("transport/live connection options were removed; use server: {url, token}");
  const client = await Client.open({ path: options.path, schema, onStore: rawHooks, ...(options.prerequisites === undefined ? {} : { prerequisites: options.prerequisites }), ...(options.migration === undefined ? {} : { migration: options.migration }), ...(options.discardPending === undefined ? {} : { discardPending: options.discardPending }) });
  try {
  const connection = options.server === undefined ? undefined : await client.connect(options.server, options.connection ?? {});
  return new GeneratedClient(client, connection);
  } catch (error) { await client.close().catch(() => {}); throw error; }
 }
 transaction<T>(body: (tx: ApplicationTransaction) => Promise<T>): Promise<T> { return this.client.transaction((tx) => body(new ApplicationTransaction(tx))); }
 /** This device's durable client identity. */
 get clientId(): string { return this.client.clientId; }
 /** The client's sync state: a local snapshot, not a network probe. */
 syncState(): Promise<ClientSyncState> { return this.client.syncState(); }
 /** Leave an incompatible database behind for a fresh file; refused while unsent work remains unless `discardPending`. */
 rebuild(options: { discardPending?: boolean } = {}): Promise<RebuildReport> { return this.client.rebuild(options); }
 /** Remove a handled rejection from the local inbox; it is not retried. */
 dismissRejection(ordinal: number): Promise<void> { return this.client.dismissRejection(ordinal); }
 /** Remove unsent work and recompute local state; frozen work cannot be dropped. */
 drop(ordinal: number): Promise<void> { return this.client.drop(ordinal); }
 pendingTasks(): Promise<RecordValue[]> { return this.client.pendingTasks(); }
 /** Mark a prerequisite task by its opaque key; `pending` runs its handler again at once. */
 setReadiness(key: string, state: "ready" | "pending" | "failed"): Promise<void> { return this.client.setReadiness(key, state); }
 /** Start the background connection when `open` was called without a server. */
 async connect(server: ServerOptions, options: ConnectionOptions = {}): Promise<Connection> { this.connection = await this.client.connect(server, options); return this.connection; }
 /** Escape hatch: an untyped structured query. */
 querySpec(model: string, query: QuerySpec = {}): Promise<RecordValue[]> { return this.client.querySpec(model, query); }
 /** Escape hatch: read-only SQL over the local database. */
 readSql(sql: string, parameters: unknown[] = []): Promise<RecordValue[]> { return this.client.readSql(sql, parameters); }
 close() { return this.client.close(); }
}
