// Generated by axton. Do not edit.
import 'dart:async';
import 'dart:convert';
import 'package:axton/axton.dart';
export 'package:axton/axton.dart' show RuntimeConnection, SyncServer, AdmissionRefused, Call, CallOutcome, CallSuccess, CallFailure, CallStatus, CallError, StoreConnection, BootstrapStatus, BootstrapPhase, BootstrapError, BootstrapFailedException, ClientClosedException, PrerequisiteRetry, PrerequisiteHandler, AxtonDateTime, RefusedAct, FailedAct, FailedTask, SubmittedAct, ActOperation;
class Present<T> { final T value; const Present(this.value); }
abstract interface class _DartActionRecord { Map<String,dynamic> toRecord(); }
final Map<String,dynamic> schema = jsonDecode('{"actions":[{"input":{"enums":[],"models":[]},"inputs":[{"cardinality":"single","kind":"value","list":false,"name":"at","nullable":false,"required":true,"type":{"kind":"scalar","name":"dateTime"}}],"name":"Clock","outputEnums":[],"outputs":[{"cardinality":"single","kind":"value","name":"at","source":"handlerValue","type":{"kind":"scalar","name":"dateTime"}}],"prerequisites":[],"requirements":[],"sequence":null,"version":1},{"input":{"enums":[],"models":[]},"inputs":[{"cardinality":"single","kind":"value","list":false,"name":"at","nullable":false,"required":true,"type":{"kind":"scalar","name":"dateTime"}}],"kind":"query","name":"Clock","outputEnums":[],"outputs":[{"cardinality":"single","kind":"value","name":"at","source":"handlerValue","type":{"kind":"scalar","name":"dateTime"}}],"prerequisites":[],"requirements":[],"sequence":null,"version":2},{"input":{"enums":[],"models":[]},"inputs":[],"kind":"mutation","name":"Ping","outputEnums":[],"outputs":[],"prerequisites":[],"requirements":[],"sequence":null,"version":1}],"clientPolicies":[],"enums":[],"models":[],"prerequisites":[],"requirements":[],"resultModels":[]}') as Map<String,dynamic>;
/// Public Action lifecycle types are owned by the SDK.
class ClockV1Input implements _DartActionRecord {
 final DateTime at;
 const ClockV1Input({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockV1HandlerOutput implements _DartActionRecord {
 final DateTime at;
 const ClockV1HandlerOutput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockHandlerInput implements _DartActionRecord {
 final DateTime at;
 const ClockHandlerInput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockInput implements _DartActionRecord {
 final DateTime at;
 const ClockInput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockOutput implements _DartActionRecord {
 final DateTime at;
 const ClockOutput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class ClockHandlerOutput implements _DartActionRecord {
 final DateTime at;
 const ClockHandlerOutput({required this.at});
 Map<String,dynamic> toRecord() => {
 'at': _dartActionEncode(at),
 };
}
class PingHandlerInput implements _DartActionRecord {
 const PingHandlerInput();
 Map<String,dynamic> toRecord() => {
 };
}
class PingInput implements _DartActionRecord {
 const PingInput();
 Map<String,dynamic> toRecord() => {
 };
}
typedef PingOutput = void;
typedef PingHandlerOutput = void;
abstract interface class MutationHandlerCall<Ctx, Args> { Ctx get ctx; Args get args; }
abstract interface class MutationHandlers<Ctx> {
 MutationClockHandlers<Ctx> get clock;
 MutationPingHandlers<Ctx> get ping;
}
abstract interface class MutationClockHandlers<Ctx> {
 Future<ClockV1HandlerOutput> v1(MutationHandlerCall<Ctx, ClockV1Input> call);
}
abstract interface class MutationPingHandlers<Ctx> {
 Future<PingHandlerOutput> v1(MutationHandlerCall<Ctx, PingHandlerInput> call);
}
abstract interface class QueryHandlerCall<Ctx, Args> { Ctx get ctx; Args get args; }
abstract interface class QueryHandlers<Ctx> {
 QueryClockHandlers<Ctx> get clock;
}
abstract interface class QueryClockHandlers<Ctx> {
 Future<ClockHandlerOutput> v2(QueryHandlerCall<Ctx, ClockHandlerInput> call);
}
dynamic _dartActionEncode(dynamic value) {
 if (value == null) return null;
 if (value is DateTime) return value.toAxtonPrecision().toIso8601String();
 if (value is Enum) return value.name;
 if (value is List) return value.map(_dartActionEncode).toList();
 if (value is _DartActionRecord) return value.toRecord();
 return value;
}
/// Named Mutations use the same owned local scope on client and transaction.
class Mutations extends TransactionMutations { Mutations(super.port); }
/// Query results are invocation snapshots.
class Queries {
 final Client client; Queries(this.client);
 Future<ClockOutput> clock({required DateTime at, bool store = true}) => this.client.invokeQuery<ClockOutput>('Clock', 2, {'at': _dartActionEncode(at)}, (value) { final row = (value as Map).cast<String,dynamic>(); return ClockOutput(at: DateTime.parse(row['at'] as String)); }, store: store);
}
class LiveModels { final Client port; LiveModels(this.port);

}
class TxModels { final WritePort port; TxModels(this.port);

}
class GeneratedTransaction { final Transaction transaction; late final TxModels models=TxModels(transaction); GeneratedTransaction(this.transaction); }
class CompanionContext { final TxModels models; CompanionContext(WritePort port) : models = TxModels(port); }
class TransactionMutations {
 final SubmitMutationPort port; TransactionMutations(this.port);
 late final PingMutation ping = PingMutation(port);
}
class PingMutation {
 final SubmitMutationPort port; PingMutation(this.port);
 Map<String,dynamic> _encode(PingInput input) => {};
 Future<Call<PingOutput>> call(PingInput input) => port.submitMutation<PingOutput>('Ping', 1, _encode(input), (_) {});
 Future<Call<PingOutput>> withTransaction(FutureOr<PingInput> Function(CompanionContext tx) body) => port.submitMutation<PingOutput>('Ping', 1, null, (_) {}, input: (port) async => _encode(await body(CompanionContext(port))));
}
class ApplicationTransaction extends GeneratedTransaction { late final TransactionMutations mutations = TransactionMutations(transaction); late final rejections = transaction.rejections; late final failures = transaction.failures; ApplicationTransaction(super.transaction); }
class GeneratedClient {
 final Client client; RuntimeConnection? get connection => client.connection; late final LiveModels models=LiveModels(client);
 late final Mutations mutations=Mutations(client);
 late final Queries queries=Queries(client);
 GeneratedClient._(this.client);
 static Future<GeneratedClient> open({required String path, required String stream, StoreConnection? connection, String? libraryPath, Map<String,PrerequisiteHandler>? prerequisites}) async => GeneratedClient._(await Client.open(path:path,stream:stream,connection:connection,schema:schema,libraryPath:libraryPath,prerequisites:prerequisites));
 Future<void> bootstrap() => client.bootstrap();
 Future<RuntimeConnection> connect(SyncServer server,{void Function(Object)? onError,Future<void> Function()? refreshAuth,Duration directTimeout=const Duration(seconds:30)}) => client.connect(server,onError:onError,refreshAuth:refreshAuth,directTimeout:directTimeout);
 Future<void> resetStore({bool discardPending=false}) => client.resetStore(discardPending:discardPending);
 Future<T> transaction<T>(Future<T> Function(ApplicationTransaction tx) body) => client.transaction((tx) => body(ApplicationTransaction(tx)));
 /// This device's durable client identity.
 String get clientId => client.clientId;
 /// The client's sync state: a local snapshot, not a network probe.
 Future<Map<String,dynamic>> syncState() => client.syncState();
 /// Leave an incompatible database behind for a fresh file; refused while unsent work remains unless [discardPending].
 Future<Map<String,dynamic>> rebuild({bool discardPending = false}) => client.rebuild(discardPending: discardPending);
 /// Remove a handled rejection from the local inbox; it is not retried.
 Future<void> dismissRejection(int ordinal) => client.dismissRejection(ordinal);
 /// Remove unsent work and recompute local state; frozen work cannot be dropped.
 Future<void> drop(int ordinal) => client.drop(ordinal);
 Future<List<Map<String,dynamic>>> pendingTasks() => client.pendingTasks();
 /// Mark a prerequisite task by its opaque key: `ready`, `pending` or `failed`; `pending` runs its handler again at once.
 Future<void> setReadiness(String key, String state) => client.setReadiness(key, state);
 /// The refusals retained until dismissed, each with the act as submitted: `watch`, `get` and `dismiss`.
 late final rejections = client.rejections;
 /// The unsent acts blocked on a terminally failed prerequisite task: `watch`, `retry` and `drop`.
 late final failures = client.failures;
 /// The queue of unsettled acts: `watchPending`.
 late final outbound = client.outbound;
 /// Escape hatch: an untyped structured query.
 Future<List<Map<String,dynamic>>> querySpec(String model, Map<String,dynamic> query) => client.querySpec(model, query);
 /// Escape hatch: read-only SQL over the local database.
 Future<List<Map<String,dynamic>>> readSql(String sql, {List<dynamic> parameters = const []}) => client.readSql(sql, parameters: parameters);
 /// Read-only SQL over several Models: the current rows, then each different result after a commit that writes a table it reads.
 Stream<List<Map<String,dynamic>>> watchSql(String sql, {List<dynamic> parameters = const []}) => client.watchSql(sql, parameters: parameters);
 Future<void> close() => client.close();
}
