// Generated by axton. Do not edit.
import type { Call, QueryOptions } from './client.ts';
export interface ReadPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; querySpec(model:string,query:object):Promise<Record<string,unknown>[]>; related(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }
export interface WritePort extends ReadPort { direct(operation:object):Promise<void>; }
export interface LivePort extends WritePort { watch(model:string,where:Record<string,unknown>,listener:(rows:Record<string,unknown>[])=>void,onError?:(error:unknown)=>void):()=>void; syncState(model:string,identity:object):Promise<unknown>; }
export interface CallPort { invokeQuery<T>(name:string,version:number,args:object,decode:(value:unknown)=>T,options?:QueryOptions):Promise<T>; }
export const schema = {"actions":[],"clientPolicies":[],"enums":[],"models":[{"fields":[{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"label","nullable":false,"type":{"kind":"scalar","name":"string"}}],"identity":["id"],"name":"Item","relations":[],"unique":[],"version":1}],"prerequisites":[],"requirements":[],"resultModels":[{"enums":[],"fields":[{"name":"id","nullable":false,"type":{"kind":"scalar","name":"string"}},{"name":"label","nullable":false,"type":{"kind":"scalar","name":"string"}}],"identity":["id"],"name":"Item","version":1}]} as const;
export type MutationName = string;
export interface PendingMutation { ordinal:number; name:MutationName; phase:'queued'|'frozen'; prerequisites:{key:string;state:'ready'|'pending'|'failed'}[]; diverged?:boolean; }
export interface Rejection { ordinal:number; code:string; [key:string]:unknown; }
export interface SyncState { pending:PendingMutation[]; rejections:Rejection[]; }
export interface Item {
 id: string;
 label: string;
}
export interface ItemIdentity {
 id: string;
}
export interface ItemPatch {
 label?: string;
}
export interface ItemCreate {
 id: string;
 label: string;
}
export function decodeItem(row:Record<string,unknown>):Item { return {
 id: row.id as string,
 label: row.label as string,
}; }
export function decodeItemIdentity(row:Record<string,unknown>):ItemIdentity { return {
 id: row.id as string,
}; }
export function encodeItem(value:Item):Record<string,unknown> { return {
 id: value.id,
 label: value.label,
}; }
export function encodeItemIdentity(value:ItemIdentity):Record<string,unknown> { return {
 id: value.id,
}; }
export function encodeItemPatch(value:ItemPatch):Record<string,unknown> { return {
 ...(value.label !== undefined ? { label: value.label } : {}),
}; }
export function encodeItemWhere(value:Partial<Item>):Record<string,unknown> { return {
 ...(value.id !== undefined ? { id: value.id } : {}),
 ...(value.label !== undefined ? { label: value.label } : {}),
}; }
export function encodeItemCreate(value:ItemCreate):Record<string,unknown> { return {
 id: value.id,
 label: value.label,
}; }
export function encodeItemCreateIdentity(value:ItemCreate):Record<string,unknown> { return {
 id: value.id,
}; }
export class ItemModel<P extends ReadPort=ReadPort> { readonly port:P; constructor(port:P) { this.port=port; }
 async get(identity:ItemIdentity):Promise<Item|null> { const row=await this.port.read('Item',encodeItemIdentity(identity)); return row===null ? null : decodeItem(row); }
 async query(options:{where?:Partial<Item>;orderBy?:{field:'id' | 'label';direction:'ascending'|'descending'}[];limit?:number}={}):Promise<Item[]> { return (await this.port.querySpec('Item',{filter:encodeItemWhere(options.where??{}),orderBy:options.orderBy??[],...(options.limit===undefined?{}:{limit:options.limit})})).map(decodeItem); }
}
export class ItemTxModel<P extends WritePort=WritePort> extends ItemModel<P> {
 create(value:ItemCreate):Promise<void> { return this.port.direct({model:'Item',op:'create',identity:encodeItemCreateIdentity(value),values:encodeItemPatch(value)}); }
 update(identity:ItemIdentity, patch:ItemPatch):Promise<void> { return this.port.direct({model:'Item',op:'update',identity:encodeItemIdentity(identity),values:encodeItemPatch(patch)}); }
 delete(identity:ItemIdentity):Promise<void> { return this.port.direct({model:'Item',op:'delete',identity:encodeItemIdentity(identity)}); }
}
export class ItemLiveModel extends ItemTxModel<LivePort> {
 watch(options:{where?:Partial<Item>}, listener:(rows:Item[])=>void, onError?:(error:unknown)=>void):()=>void { return this.port.watch('Item',encodeItemWhere(options.where??{}),(rows)=>listener(rows.map(decodeItem)),onError); }
 /** This record's sync state: its pending mutations and retained rejections. Local only. */
 async syncState(identity:ItemIdentity):Promise<SyncState> { return (await this.port.syncState('Item',encodeItemIdentity(identity))) as SyncState; }
}
export function makeMutations(_port:CallPort) { return {}; }
export function makeQueries(_port:CallPort) { return {}; }
export interface LiveModels { item:ItemLiveModel; }
export function liveModels(port:LivePort):LiveModels { return { item:new ItemLiveModel(port) }; }
export interface TxModels { item:ItemTxModel; }
export function txModels(port:WritePort):TxModels { return { item:new ItemTxModel(port) }; }
export interface FetchPort { fetchModel<T>(model:string,version:number,identity:object,decode:(row:Record<string,unknown>)=>T,options?:{store?:boolean}):Promise<T|null>; }
/** One-shot remote reads: the complete snapshot through the Model's Loader, or null. `store: false` skips local cache writes. */
export interface FetchModels {
 item(identity:ItemIdentity, options?:{store?:boolean}):Promise<Item|null>;
}
export function fetchModels(port:FetchPort):FetchModels { return {
 item:(identity,options)=>port.fetchModel('Item',1,encodeItemIdentity(identity),decodeItem,options),
}; }
export class GeneratedTransaction { readonly transaction:WritePort; readonly models:TxModels; constructor(transaction:WritePort) { this.transaction=transaction; this.models=txModels(transaction); } }
