use crate::current_operations::CurrentOperations;
use serde_json::Value;
use std::fmt::Write;
pub(crate) fn arr<'a>(v: &'a Value, k: &str) -> &'a Vec<Value> {
    v[k].as_array().unwrap()
}
pub(crate) fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v[k].as_str().unwrap()
}
/// Deprecation notices are generated-code hints only ([#91](https://github.com/zanminwang/axton/issues/91)):
/// `Some(reason)` when the field, enum value or slot carries `@deprecated`.
fn deprecation<'a>(v: &'a Value, kind: &str, keys: &[(&str, &str)]) -> Option<&'a Value> {
    v["deprecations"]
        .as_array()?
        .iter()
        .find(|d| d["kind"] == kind && keys.iter().all(|(k, x)| d[*k] == *x))
        .map(|d| &d["reason"])
}
/// A JSDoc line for a deprecated member, or nothing.
fn ts_deprecated(reason: Option<&Value>) -> String {
    match reason {
        None => String::new(),
        Some(Value::String(r)) => format!(" /** @deprecated {r} */\n"),
        Some(_) => " /** @deprecated */\n".into(),
    }
}
/// A Dart `@Deprecated` annotation for a deprecated member, or nothing.
fn dart_deprecated(reason: Option<&Value>, trailing: &str) -> String {
    match reason {
        None => String::new(),
        Some(r) => format!(
            "@Deprecated('{}'){trailing}",
            r.as_str()
                .unwrap_or("")
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
        ),
    }
}
pub(crate) fn lower(s: &str) -> String {
    let mut c = s.chars();
    format!("{}{}", c.next().unwrap().to_lowercase(), c.as_str())
}
fn ty(t: &Value, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = ty(&t["element"], dart);
        return if dart {
            format!("List<{e}>")
        } else {
            format!("{e}[]")
        };
    }
    if t["kind"] == "enum" {
        return s(t, "name").into();
    }
    match s(t, "name") {
        "boolean" => {
            if dart {
                "bool"
            } else {
                "boolean"
            }
        }
        "int" => {
            if dart {
                "int"
            } else {
                "number"
            }
        }
        "float" => {
            if dart {
                "double"
            } else {
                "number"
            }
        }
        "dateTime" => {
            if dart {
                "DateTime"
            } else {
                "Date"
            }
        }
        _ => {
            if dart {
                "String"
            } else {
                "string"
            }
        }
    }
    .into()
}
/// Whether a fresh create may omit this field: it carries a creation default.
fn defaulted(f: &Value) -> bool {
    f.get("createDefault").is_some_and(|d| !d.is_null())
}
fn ft(f: &Value, dart: bool) -> String {
    format!(
        "{}{}",
        ty(&f["type"], dart),
        if f["nullable"] == true {
            if dart { "?" } else { " | null" }
        } else {
            ""
        }
    )
}
fn decode(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = decode(&t["element"], "e", dart);
        return if dart {
            format!("({x} as List).map((e) => {e}).toList()")
        } else {
            format!("({x} as unknown[]).map(e => {e})")
        };
    }
    if t["kind"] == "enum" {
        let n = s(t, "name");
        return if dart {
            format!("{n}.values.byName({x} as String)")
        } else {
            format!("{x} as {n}")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("DateTime.parse({x} as String)")
        } else {
            format!("new Date({x} as string)")
        };
    }
    if dart && t["name"] == "float" {
        format!("({x} as num).toDouble()")
    } else {
        format!("{x} as {}", ty(t, dart))
    }
}
pub(crate) fn encoded(t: &Value, x: &str, dart: bool) -> String {
    if t["kind"] == "list" {
        let e = encoded(&t["element"], "e", dart);
        return if dart {
            format!("{x}.map((e) => {e}).toList()")
        } else {
            format!("{x}.map(e => {e})")
        };
    }
    if t["name"] == "dateTime" {
        return if dart {
            format!("{x}.toAxtonPrecision().toIso8601String()")
        } else {
            format!("{x}.toISOString()")
        };
    }
    if dart && t["kind"] == "enum" {
        format!("{x}.name")
    } else {
        x.into()
    }
}
fn enc(f: &Value, x: &str, dart: bool) -> String {
    let e = encoded(
        &f["type"],
        &if dart && f["nullable"] == true {
            format!("{x}!")
        } else {
            x.into()
        },
        dart,
    );
    if f["nullable"] == true {
        format!("{x} == null ? null : {e}")
    } else {
        e
    }
}
pub fn typescript(v: &Value) -> String {
    let current = CurrentOperations::new(v);
    let mut o = String::from(
        "// Generated by axton. Do not edit.\nimport type { Call, QueryOptions } from './client.ts';\nexport interface ReadPort { read(model:string,identity:object):Promise<Record<string,unknown>|null>; querySpec(model:string,query:object):Promise<Record<string,unknown>[]>; related(model:string,identity:object,relation:string):Promise<Record<string,unknown>|null>; referencing(model:string,identity:object,source:string,relation:string):Promise<Record<string,unknown>[]>; }\nexport interface WritePort extends ReadPort { direct(operation:object):Promise<void>; }\nexport interface LivePort extends WritePort { watch(model:string,where:Record<string,unknown>,listener:(rows:Record<string,unknown>[])=>void,onError?:(error:unknown)=>void):()=>void; syncState(model:string,identity:object):Promise<unknown>; }\nexport interface CallPort { invokeQuery<T>(name:string,version:number,args:object,decode:(value:unknown)=>T,options?:QueryOptions):Promise<T>; }\n",
    );

    writeln!(o, "export const schema = {} as const;", v["schema"]).unwrap();
    ts_sync_state(v, &mut o);
    for en in arr(&v["schema"], "enums") {
        for value in arr(en, "values") {
            if let Some(reason) = deprecation(
                v,
                "enumValue",
                &[("enum", s(en, "name")), ("value", value.as_str().unwrap())],
            ) {
                match reason {
                    Value::String(r) => writeln!(o, "/** @deprecated {value}: {r} */").unwrap(),
                    _ => writeln!(o, "/** @deprecated {value} */").unwrap(),
                }
            }
        }
        writeln!(
            o,
            "export type {} = {};",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(" | ")
        )
        .unwrap();
    }
    if let Some(models) = v["abstractModels"].as_array() {
        for m in models {
            let n = s(m, "name");
            let parent = m["parent"]
                .as_str()
                .map(|p| format!(" extends {p}"))
                .unwrap_or_default();
            writeln!(o, "export interface {n}{parent} {{").unwrap();
            for f in arr(m, "fields") {
                o.push_str(&ts_deprecated(deprecation(
                    v,
                    "field",
                    &[("model", n), ("field", s(f, "name"))],
                )));
                writeln!(o, " {}: {};", s(f, "name"), ft(f, false)).unwrap();
            }
            o.push_str("}\n");
        }
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for (suffix, filter, partial) in
            [("", 0, false), ("Identity", 1, false), ("Patch", 2, true)]
        {
            let parent = if suffix.is_empty() {
                v["inheritance"]
                    .as_array()
                    .and_then(|items| items.iter().find(|i| i["model"] == n))
                    .and_then(|i| i["parent"].as_str())
                    .map(|p| format!(" extends {p}"))
                    .unwrap_or_default()
            } else {
                String::new()
            };
            writeln!(o, "export interface {n}{suffix}{parent} {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (filter == 1 && !id) || (filter == 2 && id) {
                    continue;
                }
                o.push_str(&ts_deprecated(deprecation(
                    v,
                    "field",
                    &[("model", n), ("field", s(f, "name"))],
                )));
                writeln!(
                    o,
                    " {}{}: {};",
                    s(f, "name"),
                    if partial { "?" } else { "" },
                    ft(f, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
        // What a fresh create accepts: a field with a creation default may be
        // omitted (the client fills it once before persisting or sending).
        writeln!(o, "export interface {n}Create {{").unwrap();
        for f in arr(m, "fields") {
            o.push_str(&ts_deprecated(deprecation(
                v,
                "field",
                &[("model", n), ("field", s(f, "name"))],
            )));
            writeln!(
                o,
                " {}{}: {};",
                s(f, "name"),
                if defaulted(f) { "?" } else { "" },
                ft(f, false)
            )
            .unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "export function decode{n}(row:Record<string,unknown>):{n} {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            let k = s(f, "name");
            let x = format!("row.{k}");
            let dec = decode(&f["type"], &x, false);
            writeln!(
                o,
                " {k}: {},",
                if f["nullable"] == true {
                    format!("{x} == null ? null : {dec}")
                } else {
                    dec
                }
            )
            .unwrap();
        }
        o.push_str("}; }\n");
        writeln!(
            o,
            "export function decode{n}Identity(row:Record<string,unknown>):{n}Identity {{ return {{"
        )
        .unwrap();
        for f in arr(m, "fields") {
            if !arr(m, "identity").contains(&f["name"]) {
                continue;
            }
            let k = s(f, "name");
            let x = format!("row.{k}");
            writeln!(o, " {k}: {},", decode(&f["type"], &x, false)).unwrap();
        }
        o.push_str("}; }\n");
        for (suffix, partial) in [
            ("", false),
            ("Identity", false),
            ("Patch", true),
            ("Where", true),
        ] {
            let input = if suffix == "Where" {
                format!("Partial<{n}>")
            } else {
                format!("{n}{suffix}")
            };
            writeln!(o,"export function encode{n}{suffix}(value:{input}):Record<string,unknown> {{ return {{").unwrap();
            for f in arr(m, "fields") {
                let id = arr(m, "identity").contains(&f["name"]);
                if (suffix == "Identity" && !id) || (suffix == "Patch" && id) {
                    continue;
                }
                let k = s(f, "name");
                let ex = enc(f, &format!("value.{k}"), false);
                if partial {
                    writeln!(o, " ...(value.{k} !== undefined ? {{ {k}: {ex} }} : {{}}),").unwrap()
                } else {
                    writeln!(o, " {k}: {ex},").unwrap()
                }
            }
            o.push_str("}; }\n");
        }
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for (suffix, identity_only) in [("", false), ("Identity", true)] {
            writeln!(o, "export function encode{n}Create{suffix}(value:{n}Create):Record<string,unknown> {{ return {{").unwrap();
            for f in arr(m, "fields") {
                if identity_only && !arr(m, "identity").contains(&f["name"]) {
                    continue;
                }
                let k = s(f, "name");
                let ex = enc(f, &format!("value.{k}"), false);
                if defaulted(f) {
                    writeln!(o, " ...(value.{k} !== undefined ? {{ {k}: {ex} }} : {{}}),").unwrap()
                } else {
                    writeln!(o, " {k}: {ex},").unwrap()
                }
            }
            o.push_str("}; }\n");
        }
    }

    ts_models(v, &mut o);
    ts_actions(v, &current, &mut o);
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "LivePort"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "export interface {suffix}Models {{ {} }}",
            names
                .iter()
                .map(|(key, n)| format!("{key}:{n}{suffix}Model;"))
                .collect::<Vec<_>>()
                .join(" ")
        )
        .unwrap();
        writeln!(
            o,
            "export function {}Models(port:{port}):{suffix}Models {{ return {{ {} }}; }}",
            lower(suffix),
            names
                .iter()
                .map(|(key, n)| format!("{key}:new {n}{suffix}Model(port)"))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    ts_fetch(v, &mut o);
    o.push_str("export class GeneratedTransaction { readonly transaction:WritePort; readonly models:TxModels; constructor(transaction:WritePort) { this.transaction=transaction; this.models=txModels(transaction); } }\n");
    crate::emit_transactions::ts_generated(&current, &mut o);
    o
}
/// The typed shape of a record's sync state. Mutation names are the schema's,
/// so a pending entry's `name` is checked against them.
fn ts_sync_state(v: &Value, o: &mut String) {
    let current = crate::current_operations::CurrentOperations::new(v);
    let mut names: Vec<String> = current
        .of_kind(axton_core::CallKind::Mutation)
        .map(|(name, _, _)| format!("'{}'", name))
        .collect();
    names.sort();
    names.dedup();
    let union = if names.is_empty() {
        "string".to_string()
    } else {
        names.join("|")
    };
    writeln!(o, "export type MutationName = {union};").unwrap();
    o.push_str("export interface PendingMutation { ordinal:number; name:MutationName; phase:'queued'|'frozen'; prerequisites:{key:string;state:'ready'|'pending'|'failed'}[]; diverged?:boolean; }\n");
    o.push_str(
        "export interface Rejection { ordinal:number; code:string; [key:string]:unknown; }\n",
    );
    o.push_str(
        "export interface SyncState { pending:PendingMutation[]; rejections:Rejection[]; }\n",
    );
}

fn action_cardinality(base: &str, cardinality: &str) -> String {
    match cardinality {
        "optional" => format!("{base} | null"),
        "list" => format!("{base}[]"),
        _ => base.to_string(),
    }
}
/// A current operation input's TypeScript type. Client create operands may
/// omit defaulted fields; `handler` types are the complete values handlers receive.
pub(crate) fn action_input_type(input: &Value, handler: bool) -> String {
    if input["kind"] == "value" {
        let mut base = ty(&input["type"], false);
        if input["list"] == true {
            base.push_str("[]");
        }
        return if input["nullable"] == true {
            format!("{base} | null")
        } else {
            base
        };
    }
    let model = s(input, "model");
    let base = match s(input, "operation") {
        "create" if handler => model.to_string(),
        "create" => format!("{model}Create"),
        "delete" => format!("{model}Delete"),
        _ => {
            let keys = input["allowedPatchFields"]
                .as_array()
                .map(|fields| {
                    if fields.is_empty() {
                        "never".to_string()
                    } else {
                        fields
                            .iter()
                            .map(Value::to_string)
                            .collect::<Vec<_>>()
                            .join(" | ")
                    }
                })
                .unwrap_or_else(|| format!("keyof {model}Patch"));
            format!("{model}Update<{keys}>")
        }
    };
    action_cardinality(&base, s(input, "cardinality"))
}
fn action_output_type(output: &Value, handler: bool) -> String {
    let base = match s(output, "kind") {
        "value" => ty(&output["type"], false),
        "deleteIdentity" => format!("{}Identity", s(output, "model")),
        "model" if handler => format!("{}Identity", s(output, "model")),
        "model" => s(output, "model").to_string(),
        _ => unreachable!(),
    };
    action_cardinality(&base, s(output, "cardinality"))
}
pub(crate) fn action_type_name(action: &Value, latest: u64, suffix: &str) -> String {
    let name = s(action, "name");
    let version = action["version"].as_u64().unwrap();
    if version == latest {
        format!("{name}{suffix}")
    } else {
        format!("{name}V{version}{suffix}")
    }
}
fn snapshot_type(ty_value: &Value, enums: &Value) -> String {
    if ty_value["kind"] == "list" {
        return format!("{}[]", snapshot_type(&ty_value["element"], enums));
    }
    if ty_value["kind"] == "enum"
        && let Some(en) = enums
            .as_array()
            .and_then(|list| list.iter().find(|en| en["name"] == ty_value["name"]))
    {
        return arr(en, "values")
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    ty(ty_value, false)
}
fn snapshot_field_type(field: &Value, enums: &Value) -> String {
    let base = snapshot_type(&field["type"], enums);
    if field["nullable"] == true {
        format!("{base} | null")
    } else {
        base
    }
}
pub(crate) fn historical_action_input_type(arg: &Value, action: &Value, latest: u64) -> String {
    if action["version"].as_u64() == Some(latest) {
        return action_input_type(arg, true);
    }
    if arg["kind"] == "value" {
        let mut base = snapshot_type(&arg["type"], &action["input"]["enums"]);
        if arg["list"] == true {
            base = format!("({base})[]");
        }
        return if arg["nullable"] == true {
            format!("{base} | null")
        } else {
            base
        };
    }
    let prefix = action_type_name(action, latest, "");
    let model = s(arg, "model");
    let base = match s(arg, "operation") {
        "create" => format!("{prefix}{model}Create"),
        "delete" => format!("{prefix}{model}Identity"),
        _ => {
            let keys = arg["allowedPatchFields"]
                .as_array()
                .map(|fields| {
                    if fields.is_empty() {
                        "never".to_string()
                    } else {
                        fields
                            .iter()
                            .map(Value::to_string)
                            .collect::<Vec<_>>()
                            .join(" | ")
                    }
                })
                .unwrap_or_else(|| format!("keyof {prefix}{model}Patch"));
            format!("{prefix}{model}Update<{keys}>")
        }
    };
    action_cardinality(&base, s(arg, "cardinality"))
}
pub(crate) fn backend_action_output_type(
    field: &Value,
    action: &Value,
    models: &[Value],
) -> String {
    let base = if field["kind"] == "value" {
        snapshot_type(&field["type"], &action["outputEnums"])
    } else {
        let model = s(field, "model");
        let read_version = field["modelReadVersion"].as_u64();
        let current = models
            .iter()
            .find(|m| m["name"] == model)
            .and_then(|m| m["version"].as_u64());
        if field["kind"] == "model" && read_version != current {
            format!("{model}V{}Identity", read_version.unwrap())
        } else {
            format!("{model}Identity")
        }
    };
    if field["kind"] == "value" && field["type"]["kind"] == "enum" && field["cardinality"] == "list"
    {
        format!("({base})[]")
    } else {
        action_cardinality(&base, s(field, "cardinality"))
    }
}
fn ts_actions(v: &Value, current: &CurrentOperations<'_>, o: &mut String) {
    let actions = arr(v, "actions");
    if actions.is_empty() {
        o.push_str("export function makeMutations(_port:CallPort) { return {}; }\nexport function makeQueries(_port:CallPort) { return {}; }\n");
        return;
    }
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(o, "export type {n}Update<K extends keyof {n}Patch = keyof {n}Patch> = {n}Identity & Partial<Pick<{n}Patch, K>>;").unwrap();
        writeln!(o, "export type {n}Delete = {n}Identity;").unwrap();
    }
    for action in actions {
        let n = s(action, "name");
        let version = current.version(n);
        if action["version"].as_u64() != Some(version) {
            continue;
        }
        let input = action_type_name(action, version, "Input");
        let output = action_type_name(action, version, "Output");
        writeln!(o, "export interface {input} {{").unwrap();
        for arg in arr(action, "inputs") {
            let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
            writeln!(
                o,
                " {}{}: {};",
                s(arg, "name"),
                if optional { "?" } else { "" },
                action_input_type(arg, false)
            )
            .unwrap();
        }
        o.push_str("}\n");
        if arr(action, "outputs").is_empty() {
            writeln!(o, "export type {output} = void;").unwrap();
        } else {
            writeln!(o, "export interface {output} {{").unwrap();
            for field in arr(action, "outputs") {
                writeln!(
                    o,
                    " {}: {};",
                    s(field, "name"),
                    action_output_type(field, false)
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    for (name, _, action) in current.iter() {
        writeln!(
            o,
            "function encode{name}Input(args:{name}Input):Record<string,unknown> {{ return {{"
        )
        .unwrap();
        for input in arr(action, "inputs") {
            let key = s(input, "name");
            let expr = ts_action_encode_input(input, &format!("args.{key}"));
            writeln!(o, " {key}: {expr},").unwrap();
        }
        o.push_str("}; }\n");
        if arr(action, "outputs").is_empty() {
            writeln!(
                o,
                "function decode{name}Output(_value:unknown):void {{ return undefined; }}"
            )
            .unwrap();
        } else {
            writeln!(o, "function decode{name}Output(value:unknown):{name}Output {{ const row=value as Record<string,unknown>; return {{").unwrap();
            for output in arr(action, "outputs") {
                let key = s(output, "name");
                let expr = ts_action_decode_output(output, &format!("row.{key}"));
                writeln!(o, " {key}: {expr},").unwrap();
            }
            o.push_str("}; }\n");
        }
    }
    let queries: Vec<_> = current
        .of_kind(axton_core::CallKind::Query)
        .map(|(name, version, _)| (name, version))
        .collect();
    if !current.has_mutations() {
        o.push_str("export function makeMutations(_port:CallPort) { return {}; }\n");
    } else {
        o.push_str("/** Named Mutations commit their local scope before returning a Call. Call.wait observes backend settlement. */\nexport function makeMutations(port:SubmitMutationPort) { return makeTransactionMutations(port); }\n");
    }
    for (name, _) in &queries {
        writeln!(o, "export type {name}Options = QueryOptions;").unwrap();
    }
    o.push_str("/** Queries return invocation snapshots after permitted cache writes commit. */\nexport function makeQueries(port:CallPort) { return {\n");
    for (name, version) in &queries {
        writeln!(o, " {}: (args:{name}Input, options?:{name}Options):Promise<{name}Output> => port.invokeQuery('{name}',{version},encode{name}Input(args),decode{name}Output,options),", lower(name)).unwrap();
    }
    o.push_str("}; }\n");
}
/// The Dart named parameter carrying the store selector. It is `store`
/// unless a business input already uses that name.
pub(crate) fn dart_store_param(action: &Value) -> String {
    let taken = |name: &str| arr(action, "inputs").iter().any(|i| i["name"] == name);
    let mut name = if taken("store") {
        "outputStore".to_string()
    } else {
        "store".to_string()
    };
    while taken(&name) {
        name.push('$');
    }
    name
}
pub(crate) fn ts_action_encode_input(input: &Value, x: &str) -> String {
    if input["kind"] == "value" {
        let ty = if input["list"] == true {
            serde_json::json!({"kind":"list","element":input["type"]})
        } else {
            input["type"].clone()
        };
        let expr = encoded(&ty, x, false);
        return if input["nullable"] == true {
            format!("{x} === null ? null : {expr}")
        } else {
            expr
        };
    }
    match s(input, "cardinality") {
        "list" => format!(
            "{x}.map(value => {})",
            ts_action_encode_model_one(input, "value")
        ),
        "optional" => format!(
            "{x} == null ? null : {}",
            ts_action_encode_model_one(input, x)
        ),
        _ => ts_action_encode_model_one(input, x),
    }
}
fn ts_action_encode_model_one(input: &Value, x: &str) -> String {
    let model = s(input, "model");
    match s(input, "operation") {
        "create" => format!("encode{model}Create({x})"),
        "update" => format!("({{...encode{model}Identity({x}),...encode{model}Patch({x})}})"),
        "delete" => format!("encode{model}Identity({x})"),
        _ => unreachable!(),
    }
}
fn ts_action_decode_output(output: &Value, x: &str) -> String {
    match s(output, "cardinality") {
        "list" => format!(
            "({x} as unknown[]).map(value => {})",
            ts_action_decode_one(output, "value")
        ),
        "optional" => format!("{x} == null ? null : {}", ts_action_decode_one(output, x)),
        _ => ts_action_decode_one(output, x),
    }
}
fn ts_action_decode_one(output: &Value, x: &str) -> String {
    match s(output, "kind") {
        "value" => decode(&output["type"], x, false),
        "model" => format!(
            "decode{}({x} as Record<string,unknown>)",
            s(output, "model")
        ),
        "deleteIdentity" => format!(
            "decode{}Identity({x} as Record<string,unknown>)",
            s(output, "model")
        ),
        _ => unreachable!(),
    }
}
/// Client entry point bound to the compiled schema. `runtime` is the import specifier of `@axtonjs/client`.
pub fn client_typescript(v: &Value, runtime: &str) -> String {
    let current = CurrentOperations::new(v);
    let mut o = String::from("// Generated by axton. Do not edit.\n");
    writeln!(o, "import {{ Client, type ClientSyncState, type Connection, type ConnectionOptions, type ServerOptions, type PrerequisiteHandler, type QuerySpec, type RecordValue, type StoreConnection }} from \"{runtime}\";").unwrap();
    writeln!(o, "export {{ AdmissionRefused, CallError, PrerequisiteRetry, type Call, type CallOptions, type QueryOptions, type CallOutcome, type CallStatus, type PrerequisiteHandler, type ServerOptions, type StoreConnection, type Connection, type ConnectionOptions, type BootstrapPhase, type BootstrapStatus, type ActOperation, type FailedAct, type FailedTask, type RefusedAct, type SubmittedAct }} from \"{runtime}\";").unwrap();
    let transaction = crate::emit_transactions::transaction_type(&current);
    let tx_import = if transaction == "GeneratedTransaction" {
        String::new()
    } else {
        format!(", {transaction}")
    };
    writeln!(o, "import {{ schema, liveModels, makeMutations, makeQueries, GeneratedTransaction{tx_import}, type LiveModels }} from \"./generated.ts\";").unwrap();
    let fetch = has_models(v);
    if fetch {
        o.push_str("import { fetchModels, type FetchModels } from './generated.ts';\n");
    }
    o.push_str("export * from './generated.ts';\nexport class GeneratedClient {\n readonly client: Client;\n get connection():Connection|undefined { return this.client.connection; }\n readonly models: LiveModels;\n readonly mutations: ReturnType<typeof makeMutations>;\n readonly queries: ReturnType<typeof makeQueries>;\n");
    if fetch {
        o.push_str(" readonly fetch: FetchModels;\n");
    }
    writeln!(o, " private constructor(client: Client) {{ this.client=client; this.models=liveModels(client); this.mutations=makeMutations(client); this.queries=makeQueries(client); {} }}", if fetch { "this.fetch=fetchModels(client);" } else { "" }).unwrap();
    o.push_str(" static async open(options: {path:string; stream:string; connection?:StoreConnection; prerequisites?:Record<string,PrerequisiteHandler>}):Promise<GeneratedClient> { return new GeneratedClient(await Client.open({...options,schema})); }\n bootstrap():Promise<void> { return this.client.bootstrap(); }\n connect(server:ServerOptions,options?:ConnectionOptions):Promise<Connection> { return this.client.connect(server,options); }\n resetStore(options:{discardPending?:boolean}={}):Promise<void> { return this.client.resetStore(options); }\n");
    writeln!(o, " transaction<T>(body: (tx: {transaction}) => Promise<T>): Promise<T> {{ return this.client.transaction((tx) => body(new {transaction}(tx))); }}").unwrap();
    o.push_str(" /** This device's durable client identity. */\n get clientId(): string { return this.client.clientId; }\n /** The client's sync state: a local snapshot, not a network probe. */\n syncState(): Promise<ClientSyncState> { return this.client.syncState(); }\n");
    o.push_str(" /** Remove a handled rejection from the local inbox; it is not retried. */\n dismissRejection(ordinal: number): Promise<void> { return this.client.dismissRejection(ordinal); }\n");
    o.push_str(" /** Remove unsent work and recompute local state; frozen work cannot be dropped. */\n drop(ordinal: number): Promise<void> { return this.client.drop(ordinal); }\n");
    o.push_str(" pendingTasks(): Promise<RecordValue[]> { return this.client.pendingTasks(); }\n");
    o.push_str(" /** Mark a prerequisite task by its opaque key; `pending` runs its handler again at once. */\n setReadiness(key: string, state: \"ready\" | \"pending\" | \"failed\"): Promise<void> { return this.client.setReadiness(key, state); }\n");
    o.push_str(" /** The refusals retained until dismissed, each with the act as submitted: `watch`, `get` and `dismiss`. */\n get rejections(): Client[\"rejections\"] { return this.client.rejections; }\n /** The unsent acts blocked on a terminally failed prerequisite task: `watch`, `retry` and `drop`. */\n get failures(): Client[\"failures\"] { return this.client.failures; }\n /** The queue of unsettled acts: `watchPending`. */\n get outbound(): Client[\"outbound\"] { return this.client.outbound; }\n");
    o.push_str(" /** Escape hatch: an untyped structured query. */\n querySpec(model: string, query: QuerySpec = {}): Promise<RecordValue[]> { return this.client.querySpec(model, query); }\n");
    o.push_str(" /** Escape hatch: read-only SQL over the local database. */\n readSql(sql: string, parameters: unknown[] = []): Promise<RecordValue[]> { return this.client.readSql(sql, parameters); }\n");
    o.push_str(" /** Read-only SQL over several Models, re-run after every commit that writes a table it reads: `listener` receives the current rows, then each different result. Returns a function that stops it. */\n watchSql(sql: string, parameters: unknown[] = [], listener: (rows: RecordValue[]) => void, onError?: (error: unknown) => void): () => void { return this.client.watchSql(sql, parameters, listener, onError); }\n");
    o.push_str(" close() { return this.client.close(); }\n}\n");
    o
}
/// Backend surface bound to the compiled schema. `runtime` is the import specifier of `@axtonjs/server`.
pub fn backend_typescript(v: &Value, runtime: &str) -> String {
    let mut o = String::from("// Generated by axton. Do not edit.\n");
    let has_actions = !arr(v, "actions").is_empty();
    writeln!(o, "import {{ createBackend as createRuntimeBackend, type BackendOptions, type LoaderCall }} from \"{runtime}\";").unwrap();
    if arr(v, "mutations").is_empty() {
        writeln!(
            o,
            "export {{ CallRejected, devAuth, type LoaderCall }} from \"{runtime}\";"
        )
        .unwrap();
    } else {
        writeln!(o, "export {{ CallRejected, MutationRejected, devAuth, type LoaderCall }} from \"{runtime}\";").unwrap();
    }
    let models = arr(&v["schema"], "models");
    let names: Vec<String> = models
        .iter()
        .flat_map(|m| {
            let n = s(m, "name");
            [
                format!("{n} as {n}Record"),
                format!("{n}Identity"),
                format!("{n}Patch"),
            ]
        })
        .collect();
    let mut names = names;
    if has_actions {
        for en in arr(&v["schema"], "enums") {
            names.push(s(en, "name").to_string());
        }
    }
    if has_actions {
        for m in models {
            let n = s(m, "name");
            names.extend([format!("{n}Update"), format!("{n}Delete")]);
        }
    }
    writeln!(
        o,
        "import type {{ {} }} from \"./generated.ts\";",
        names.join(", ")
    )
    .unwrap();
    for m in models {
        let n = s(m, "name");
        writeln!(o, "export type {n} = {n}Record;").unwrap();
        writeln!(o, "export type {{ {n}Identity, {n}Patch }};").unwrap();
        writeln!(o, "export function {n}(identity: {n}Identity): Extract<RecordRef, {{ model: \"{n}\" }}> {{ return {{ model: \"{n}\", identity }}; }}").unwrap();
    }
    ts_declarations(models, &mut o);
    let mut backend = v.clone();
    backend.as_object_mut().unwrap().remove("mutations");
    backend.as_object_mut().unwrap().remove("backendMutations");
    if let Some(history) = v.get("backendModels") {
        backend["models"] = history.clone();
        backend.as_object_mut().unwrap().remove("backendModels");
    }
    writeln!(o, "const schema = {} as const;", backend).unwrap();
    let actions = arr(v, "actions");
    let current = CurrentOperations::new(v);
    if has_actions {
        o.push_str("/** Trusted framework context and caller-supplied arguments of a Mutation. */\nexport type MutationHandlerCall<Tx, Args> = { ctx: MutationContext<Tx>; args: Args };\n/** A Query's context has no `stream` or `invalidate`: it reads without business side effects. */\nexport type QueryHandlerCall<Tx, Args> = { ctx: QueryContext<Tx>; args: Args };\n");
        for action in actions {
            let latest = current.version(s(action, "name"));
            if action["version"].as_u64() != Some(latest) {
                let prefix = action_type_name(action, latest, "");
                for model in arr(&action["input"], "models") {
                    let n = s(model, "name");
                    for (suffix, identity_only, patch_only) in [
                        ("Create", false, false),
                        ("Identity", true, false),
                        ("Patch", false, true),
                    ] {
                        writeln!(o, "export interface {prefix}{n}{suffix} {{").unwrap();
                        for field in arr(model, "fields") {
                            let is_id = arr(model, "identity").contains(&field["name"]);
                            if (identity_only && !is_id) || (patch_only && is_id) {
                                continue;
                            }
                            writeln!(
                                o,
                                " {}{}: {};",
                                s(field, "name"),
                                if patch_only { "?" } else { "" },
                                snapshot_field_type(field, &action["input"]["enums"])
                            )
                            .unwrap();
                        }
                        o.push_str("}\n");
                    }
                    writeln!(o, "export type {prefix}{n}Update<K extends keyof {prefix}{n}Patch = keyof {prefix}{n}Patch> = {prefix}{n}Identity & Partial<Pick<{prefix}{n}Patch, K>>;").unwrap();
                }
            }
            let input = action_type_name(action, latest, "Input");
            let output = action_type_name(action, latest, "HandlerOutput");
            writeln!(o, "export interface {input} {{").unwrap();
            for arg in arr(action, "inputs") {
                let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
                writeln!(
                    o,
                    " {}{}: {};",
                    s(arg, "name"),
                    if optional { "?" } else { "" },
                    historical_action_input_type(arg, action, latest)
                )
                .unwrap();
            }
            o.push_str("}\n");
            if arr(action, "outputs")
                .iter()
                .all(|field| field["source"].is_object())
            {
                writeln!(o, "export type {output} = void;").unwrap();
            } else {
                writeln!(o, "export interface {output} {{").unwrap();
                for field in arr(action, "outputs") {
                    if field["source"].is_object() {
                        continue;
                    }
                    writeln!(
                        o,
                        " {}: {};",
                        s(field, "name"),
                        backend_action_output_type(field, action, models)
                    )
                    .unwrap();
                }
                o.push_str("}\n");
            }
        }
    }
    // Operation registration follows each retained version's own kind, so a
    // name that changed kind at a new version registers each version under
    // its matching map. A bare function is shorthand only when the group
    // holds v1 alone.
    let mut groups = [false, false];
    for (index, (kind, interface, call)) in [
        (
            axton_core::CallKind::Mutation,
            "Mutations",
            "MutationHandlerCall",
        ),
        (axton_core::CallKind::Query, "Queries", "QueryHandlerCall"),
    ]
    .into_iter()
    .enumerate()
    {
        writeln!(o, "export interface {interface}<Tx> {{").unwrap();
        for (name, _, _) in current.iter() {
            let mut versions: Vec<&Value> = actions
                .iter()
                .filter(|a| s(a, "name") == name && crate::action_names::kind(a) == kind)
                .collect();
            if versions.is_empty() {
                continue;
            }
            groups[index] = true;
            versions.sort_by_key(|a| a["version"].as_u64().unwrap());
            let members = versions
                .iter()
                .map(|a| {
                    let input = action_type_name(a, current.version(name), "Input");
                    let output = action_type_name(a, current.version(name), "HandlerOutput");
                    format!(
                        "v{}(call: {call}<Tx, {input}>): Promise<{output}>;",
                        a["version"].as_u64().unwrap()
                    )
                })
                .collect::<Vec<_>>()
                .join(" ");
            let grouped = format!("{{ {} }}", members.trim_end_matches(';'));
            if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
                let input = action_type_name(versions[0], current.version(name), "Input");
                let output = action_type_name(versions[0], current.version(name), "HandlerOutput");
                writeln!(
                    o,
                    " {}: {grouped} | ((call: {call}<Tx, {input}>) => Promise<{output}>);",
                    lower(name)
                )
                .unwrap();
            } else {
                writeln!(o, " {}: {grouped};", lower(name)).unwrap();
            }
        }
        o.push_str("}\n");
    }

    // Every retained model read contract: the schema's own version is the
    // latest and keeps the plain record name; an older version is its own
    // record type with the enum values of its time inline, so a loader of that
    // version cannot be typed against a value the contract never promised.
    let retained: Vec<Value> = match backend.get("models").and_then(Value::as_array) {
        Some(list) => list.clone(),
        None => models
            .iter()
            .map(|m| {
                let mut snapshot = m.clone();
                snapshot["enums"] = arr(&v["schema"], "enums")
                    .iter()
                    .filter(|e| {
                        arr(m, "fields")
                            .iter()
                            .any(|f| f["type"]["kind"] == "enum" && f["type"]["name"] == e["name"])
                    })
                    .cloned()
                    .collect();
                snapshot
            })
            .collect(),
    };
    let record_name = |contract: &Value| {
        let n = s(contract, "name");
        let current = models
            .iter()
            .find(|m| m["name"] == contract["name"])
            .map(|m| m["version"].as_u64().unwrap_or(1));
        if Some(contract["version"].as_u64().unwrap()) == current {
            n.to_string()
        } else {
            format!("{n}V{}", contract["version"])
        }
    };
    for contract in &retained {
        let name = record_name(contract);
        if name == s(contract, "name") {
            continue;
        }
        writeln!(o, "export interface {name}Identity {{").unwrap();
        for f in arr(contract, "fields") {
            if arr(contract, "identity").contains(&f["name"]) {
                writeln!(
                    o,
                    " {}: {};",
                    s(f, "name"),
                    snapshot_field_type(f, &contract["enums"])
                )
                .unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "export interface {name} {{").unwrap();
        for f in arr(contract, "fields") {
            let field_type = if f["type"]["kind"] == "enum" {
                let en = arr(contract, "enums")
                    .iter()
                    .find(|e| e["name"] == f["type"]["name"])
                    .expect("a retained contract carries the enums its fields use");
                format!(
                    "{}{}",
                    arr(en, "values")
                        .iter()
                        .map(Value::to_string)
                        .collect::<Vec<_>>()
                        .join(" | "),
                    if f["nullable"] == true { " | null" } else { "" }
                )
            } else {
                ft(f, false)
            };
            writeln!(o, " {}: {field_type};", s(f, "name")).unwrap();
        }
        o.push_str("}\n");
    }
    // Loader registration mirrors handlers: every retained version under the
    // model name, a bare function only for a v1-only model. Each member is
    // optional: a Model without a Loader is device-only (#187), and the
    // backend refuses at startup a descriptor that would put it on the wire.
    // `| undefined` keeps `Loaders<Tx>["model"]` assignable back to its member
    // under `exactOptionalPropertyTypes`; the runtime reads it as omitted.
    o.push_str("export interface Loaders<Tx> {\n");
    for m in models {
        let n = s(m, "name");
        let mut versions: Vec<&Value> =
            retained.iter().filter(|c| c["name"] == m["name"]).collect();
        versions.sort_by_key(|c| c["version"].as_u64().unwrap());
        let members: Vec<String> = versions
            .iter()
            .map(|c| {
                format!(
                    "v{}(call: LoaderCall<Tx, {}Identity>): Promise<readonly ({} | null)[]>;",
                    c["version"].as_u64().unwrap(),
                    record_name(c),
                    record_name(c)
                )
            })
            .collect();
        let grouped = format!("{{ {} }}", members.join(" ").trim_end_matches(';'));
        if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
            writeln!(
                o,
                " {}?: {grouped} | ((call: LoaderCall<Tx, {n}Identity>) => Promise<readonly ({n} | null)[]>) | undefined;",
                lower(n)
            )
            .unwrap();
        } else {
            writeln!(o, " {}?: {grouped} | undefined;", lower(n)).unwrap();
        }
    }
    o.push_str("}\n");
    o.push_str("export interface PreparationContext<Tx> { tx:Tx; userId:string; streams(names:readonly string[]):Stream; invalidate:RecordDeclaration; }\nexport interface LoaderHooks<Tx> {\n");
    for model in models {
        let name = s(model, "name");
        writeln!(o," {}?: {{ prepareForViewer(call:LoaderCall<Tx,{name}Identity> & PreparationContext<Tx>):Promise<void> }};",lower(name)).unwrap();
    }
    o.push_str("}\n");
    let optional = |present: bool| if present { "" } else { "?" };
    writeln!(o, "export type Options<Tx> = Omit<BackendOptions<Tx>, \"config\" | \"mutations\" | \"queries\" | \"loaders\" | \"bootstrap\" | \"loaderHooks\" | \"protocol5\"> & {{ mutations{}: Mutations<Tx>; queries{}: Queries<Tx>; loaders: Loaders<Tx>; protocol5: NonNullable<BackendOptions<Tx>[\"protocol5\"]>; bootstrap?: (call: {{ctx: QueryContext<Tx>}}) => void | Promise<void>; loaderHooks?:LoaderHooks<Tx> }};", optional(groups[0]),optional(groups[1])).unwrap();
    o.push_str("export function createBackend<Tx>(options:Options<Tx>) { const {bootstrap,loaderHooks,...rest}=options;\n");
    o.push_str(" return createRuntimeBackend<Tx,TransactionCall<Tx>>({...rest,config:schema, mutations:options.mutations as unknown as BackendOptions<Tx>['mutations'],queries:options.queries as unknown as BackendOptions<Tx>['queries'],loaders:options.loaders as unknown as BackendOptions<Tx>['loaders'],...(bootstrap===undefined?{}:{bootstrap:bootstrap as unknown as NonNullable<BackendOptions<Tx>['bootstrap']>}),...(loaderHooks===undefined?{}:{loaderHooks:loaderHooks as unknown as NonNullable<BackendOptions<Tx>['loaderHooks']>})});\n}\n");
    o
}
/// The generated declaration API ([#140](https://github.com/zanminwang/axton/issues/140)):
/// a discriminated `RecordRef`, typed Stream tracking and invalidation
/// under each Model's lower-first accessor, and the concrete contexts
/// that carry them. A Query context carries neither.
fn ts_declarations(models: &[Value], o: &mut String) {
    let refs: Vec<String> = models
        .iter()
        .map(|m| {
            let n = s(m, "name");
            format!("{{ readonly model: \"{n}\"; readonly identity: {n}Identity }}")
        })
        .collect();
    writeln!(
        o,
        "export type RecordRef = {};",
        if refs.is_empty() {
            "never".to_string()
        } else {
            refs.join(" | ")
        }
    )
    .unwrap();
    crate::emit_stream::backend(models, o);
    o.push_str("export interface MutationContext<Tx> {\n tx: Tx;\n userId: string;\n callId: string;\n readonly stream: Stream;\n streams(names: readonly string[]): Stream;\n invalidate: RecordDeclaration;\n}\n");
    o.push_str(
        "export interface QueryContext<Tx> {\n tx: Tx;\n userId: string;\n callId: string;\n readonly stream: LoadStream;\n streams(names: readonly string[]): LoadStream;\n}\n",
    );
    o.push_str("export interface TransactionCall<Tx> {\n tx: Tx;\n streams(names: readonly string[]): Stream;\n invalidate: RecordDeclaration;\n}\n");
}
fn dart_action_type(ty_value: &Value) -> String {
    ty(ty_value, true)
}
fn dart_snapshot_type(ty_value: &Value, prefix: &str, enums: &Value) -> String {
    if ty_value["kind"] == "list" {
        return format!(
            "List<{}>",
            dart_snapshot_type(&ty_value["element"], prefix, enums)
        );
    }
    if ty_value["kind"] == "enum"
        && enums
            .as_array()
            .is_some_and(|items| items.iter().any(|e| e["name"] == ty_value["name"]))
    {
        return format!("{prefix}{}", s(ty_value, "name"));
    }
    dart_action_type(ty_value)
}
fn dart_snapshot_field(field: &Value, prefix: &str, enums: &Value) -> String {
    let base = dart_snapshot_type(&field["type"], prefix, enums);
    if field["nullable"] == true {
        format!("{base}?")
    } else {
        base
    }
}
fn dart_action_cardinality(base: &str, cardinality: &str) -> String {
    match cardinality {
        "optional" => format!("{base}?"),
        "list" => format!("List<{base}>"),
        _ => base.to_string(),
    }
}
/// An operation input's Dart type. A current create operand is a
/// `{Model}CreateInput` for the `client`, which may omit defaulted fields;
/// handlers receive the complete record.
pub(crate) fn dart_action_input_type(
    arg: &Value,
    prefix: &str,
    restriction_prefix: &str,
    enums: &Value,
    restricted: bool,
    client: bool,
) -> String {
    if arg["kind"] == "value" {
        let base = dart_snapshot_type(&arg["type"], prefix, enums);
        return if arg["list"] == true {
            format!("List<{base}>")
        } else if arg["nullable"] == true {
            format!("{base}?")
        } else {
            base
        };
    }
    let model = s(arg, "model");
    let base = match s(arg, "operation") {
        "create" if !prefix.is_empty() => format!("{prefix}{model}Create"),
        "create" if client => format!("{model}CreateInput"),
        "create" => model.to_string(),
        "delete" => format!("{prefix}{model}Delete"),
        "update" if restricted => format!(
            "{restriction_prefix}{}{}Update",
            upper(s(arg, "name")),
            if prefix.is_empty() { "" } else { "Slot" }
        ),
        "update" => format!("{prefix}{model}Update"),
        _ => unreachable!(),
    };
    dart_action_cardinality(&base, s(arg, "cardinality"))
}
fn dart_action_output_type(
    field: &Value,
    identity: bool,
    output_prefix: &str,
    output_enums: &Value,
    models: &[Value],
) -> String {
    let base = match s(field, "kind") {
        "value" => dart_snapshot_type(&field["type"], output_prefix, output_enums),
        "deleteIdentity" => format!("{}Identity", s(field, "model")),
        "model" if identity => {
            let model = s(field, "model");
            let current = models
                .iter()
                .find(|m| m["name"] == model)
                .and_then(|m| m["version"].as_u64());
            let read = field["modelReadVersion"].as_u64();
            match read {
                Some(version) if Some(version) != current => {
                    format!("{model}V{version}Identity")
                }
                _ => format!("{model}Identity"),
            }
        }
        "model" => s(field, "model").to_string(),
        _ => unreachable!(),
    };
    dart_action_cardinality(&base, s(field, "cardinality"))
}

fn dart_data_class(o: &mut String, name: &str, fields: &[(String, String, bool)]) {
    writeln!(o, "class {name} implements _DartActionRecord {{").unwrap();
    for (field, ty, _) in fields {
        writeln!(o, " final {ty} {field};").unwrap();
    }
    let params = fields
        .iter()
        .map(|(field, _, required)| {
            format!("{}this.{field}", if *required { "required " } else { "" })
        })
        .collect::<Vec<_>>()
        .join(",");
    writeln!(
        o,
        " const {name}({});",
        if fields.is_empty() {
            String::new()
        } else {
            format!("{{{params}}}")
        }
    )
    .unwrap();
    o.push_str(" Map<String,dynamic> toRecord() => {\n");
    for (field, ty, _) in fields {
        if ty.starts_with("Present<") {
            writeln!(
                o,
                " if ({field} != null) '{field}': _dartActionEncode({field}!.value),"
            )
            .unwrap();
        } else {
            writeln!(o, " '{field}': _dartActionEncode({field}),").unwrap();
        }
    }
    o.push_str(" };\n}\n");
}
fn dart_action_update(
    o: &mut String,
    name: &str,
    model: &Value,
    allowed: Option<&Vec<Value>>,
    prefix: &str,
    enums: &Value,
) {
    let mut fields = vec![];
    for field in arr(model, "fields") {
        let key = s(field, "name");
        if arr(model, "identity").contains(&field["name"]) {
            fields.push((
                key.to_string(),
                dart_snapshot_field(field, prefix, enums),
                true,
            ));
        } else if allowed.is_none_or(|a| a.contains(&field["name"])) {
            fields.push((
                key.to_string(),
                format!("Present<{}>?", dart_snapshot_field(field, prefix, enums)),
                false,
            ));
        }
    }
    dart_data_class(o, name, &fields);
}
fn dart_actions(v: &Value, current: &CurrentOperations<'_>, o: &mut String) {
    let actions = arr(v, "actions");
    if actions.is_empty() {
        return;
    }
    o.push_str("/// Public Action lifecycle types are owned by the SDK.\n");
    let models = arr(&v["schema"], "models");
    for model in models {
        let n = s(model, "name");
        writeln!(o, "typedef {n}Delete = {n}Identity;").unwrap();
        dart_action_update(o, &format!("{n}Update"), model, None, "", &Value::Null);
    }
    let mut emitted_reads = std::collections::BTreeSet::new();
    for model in v
        .get("backendModels")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        let name = s(model, "name");
        let version = model["version"].as_u64().unwrap_or(1);
        let current = models
            .iter()
            .find(|m| m["name"] == name)
            .and_then(|m| m["version"].as_u64());
        if Some(version) == current || !emitted_reads.insert((name.to_string(), version)) {
            continue;
        }
        let fields = arr(model, "fields")
            .iter()
            .filter(|field| arr(model, "identity").contains(&field["name"]))
            .map(|field| (s(field, "name").to_string(), ft(field, true), true))
            .collect::<Vec<_>>();
        dart_data_class(o, &format!("{name}V{version}Identity"), &fields);
    }
    for action in actions {
        let name = s(action, "name");
        let is_latest = action["version"].as_u64() == Some(current.version(name));
        let prefix = action_type_name(action, current.version(name), "");
        let historical = if is_latest { "" } else { prefix.as_str() };
        let input_enums = if is_latest {
            &Value::Null
        } else {
            &action["input"]["enums"]
        };
        if !is_latest {
            let mut seen = std::collections::BTreeSet::new();
            for en in input_enums.as_array().into_iter().flatten() {
                let name = s(en, "name");
                if seen.insert(name) {
                    writeln!(
                        o,
                        "enum {prefix}{name} {{ {} }}",
                        arr(en, "values")
                            .iter()
                            .map(Value::as_str)
                            .map(Option::unwrap)
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                    .unwrap();
                }
            }
            for model in arr(&action["input"], "models") {
                let model_name = s(model, "name");
                for (suffix, identity_only) in
                    [("Create", false), ("Identity", true), ("Delete", true)]
                {
                    let fields = arr(model, "fields")
                        .iter()
                        .filter(|field| {
                            !identity_only || arr(model, "identity").contains(&field["name"])
                        })
                        .map(|field| {
                            (
                                s(field, "name").to_string(),
                                dart_snapshot_field(field, &prefix, input_enums),
                                true,
                            )
                        })
                        .collect::<Vec<_>>();
                    dart_data_class(o, &format!("{prefix}{model_name}{suffix}"), &fields);
                }
                dart_action_update(
                    o,
                    &format!("{prefix}{model_name}Update"),
                    model,
                    None,
                    &prefix,
                    input_enums,
                );
            }
        }
        for arg in arr(action, "inputs") {
            if arg["kind"] == "model"
                && arg["operation"] == "update"
                && arg["allowedPatchFields"].is_array()
            {
                let model = action["input"]["models"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .chain(models.iter())
                    .find(|m| m["name"] == arg["model"])
                    .unwrap();
                dart_action_update(
                    o,
                    &format!(
                        "{prefix}{}{}Update",
                        upper(s(arg, "name")),
                        if is_latest { "" } else { "Slot" }
                    ),
                    model,
                    arg["allowedPatchFields"].as_array(),
                    historical,
                    input_enums,
                );
            }
        }
        let inputs = arr(action, "inputs")
            .iter()
            .map(|arg| {
                let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
                (
                    s(arg, "name").to_string(),
                    dart_action_input_type(
                        arg,
                        historical,
                        &prefix,
                        input_enums,
                        arg["allowedPatchFields"].is_array(),
                        false,
                    ),
                    !optional,
                )
            })
            .collect::<Vec<_>>();
        if is_latest {
            dart_data_class(o, &format!("{prefix}HandlerInput"), &inputs);
            let client_inputs = arr(action, "inputs")
                .iter()
                .map(|arg| {
                    let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
                    (
                        s(arg, "name").to_string(),
                        dart_action_input_type(
                            arg,
                            historical,
                            &prefix,
                            input_enums,
                            arg["allowedPatchFields"].is_array(),
                            true,
                        ),
                        !optional,
                    )
                })
                .collect::<Vec<_>>();
            dart_data_class(o, &format!("{prefix}Input"), &client_inputs);
        } else {
            dart_data_class(o, &format!("{prefix}Input"), &inputs);
        }

        let outputs = arr(action, "outputs");
        let output_prefix = if is_latest {
            String::new()
        } else {
            format!("{prefix}Output")
        };
        let output_enums = if is_latest {
            &Value::Null
        } else {
            &action["outputEnums"]
        };
        if !is_latest {
            let mut seen = std::collections::BTreeSet::new();
            for en in output_enums.as_array().into_iter().flatten() {
                let name = s(en, "name");
                if seen.insert(name) {
                    writeln!(
                        o,
                        "enum {output_prefix}{name} {{ {} }}",
                        arr(en, "values")
                            .iter()
                            .map(Value::as_str)
                            .map(Option::unwrap)
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                    .unwrap();
                }
            }
        }
        if is_latest {
            if outputs.is_empty() {
                writeln!(o, "typedef {prefix}Output = void;").unwrap();
            } else {
                let fields = outputs
                    .iter()
                    .map(|field| {
                        (
                            s(field, "name").to_string(),
                            dart_action_output_type(field, false, "", &Value::Null, models),
                            true,
                        )
                    })
                    .collect::<Vec<_>>();
                dart_data_class(o, &format!("{prefix}Output"), &fields);
            }
        }
        let explicit = outputs
            .iter()
            .filter(|field| !field["source"].is_object())
            .collect::<Vec<_>>();
        if explicit.is_empty() {
            writeln!(o, "typedef {prefix}HandlerOutput = void;").unwrap();
        } else {
            let fields = explicit
                .iter()
                .map(|field| {
                    (
                        s(field, "name").to_string(),
                        dart_action_output_type(field, true, &output_prefix, output_enums, models),
                        true,
                    )
                })
                .collect::<Vec<_>>();
            dart_data_class(o, &format!("{prefix}HandlerOutput"), &fields);
        }
    }

    // Handler contracts group each retained version under its own kind.
    for (kind, label) in [
        (axton_core::CallKind::Mutation, "Mutation"),
        (axton_core::CallKind::Query, "Query"),
    ] {
        let of_kind = |name: &str| -> Vec<&Value> {
            actions
                .iter()
                .filter(|a| s(a, "name") == name && crate::action_names::kind(a) == kind)
                .collect()
        };
        writeln!(o, "abstract interface class {label}HandlerCall<Ctx, Args> {{ Ctx get ctx; Args get args; }}\nabstract interface class {label}Handlers<Ctx> {{").unwrap();
        for (name, _, _) in current.iter() {
            if !of_kind(name).is_empty() {
                writeln!(o, " {label}{}Handlers<Ctx> get {};", name, lower(name)).unwrap();
            }
        }
        o.push_str("}\n");
        for (name, version, _) in current.iter() {
            if of_kind(name).is_empty() {
                continue;
            }
            writeln!(o, "abstract interface class {label}{name}Handlers<Ctx> {{").unwrap();
            for action in of_kind(name) {
                let prefix = action_type_name(action, version, "");
                writeln!(
                    o,
                    " Future<{prefix}HandlerOutput> v{}({label}HandlerCall<Ctx, {prefix}{}> call);",
                    action["version"],
                    if action["version"].as_u64() == Some(version) {
                        "HandlerInput"
                    } else {
                        "Input"
                    }
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
}
fn dart_action_decode_field(field: &Value, value: &str) -> String {
    let one = |x: &str| -> String {
        match s(field, "kind") {
            "value" => decode(&field["type"], x, true),
            "model" => format!(
                "{}.fromRecord(({x} as Map).cast<String,dynamic>())",
                s(field, "model")
            ),
            "deleteIdentity" => format!(
                "{}Identity.fromRecord(({x} as Map).cast<String,dynamic>())",
                s(field, "model")
            ),
            _ => unreachable!(),
        }
    };
    let cardinality = s(field, "cardinality");
    if cardinality == "list" {
        return format!("({value} as List).map((e) => {}).toList()", one("e"));
    }
    if cardinality == "optional" || (field["kind"] == "value" && field["nullable"] == true) {
        return format!("{value} == null ? null : {}", one(value));
    }
    one(value)
}
fn dart_action_runtime(v: &Value, current: &CurrentOperations<'_>, o: &mut String) {
    let actions = arr(v, "actions");
    if actions.is_empty() {
        return;
    }
    o.push_str("dynamic _dartActionEncode(dynamic value) {\n if (value == null) return null;\n if (value is DateTime) return value.toAxtonPrecision().toIso8601String();\n if (value is Enum) return value.name;\n if (value is List) return value.map(_dartActionEncode).toList();\n if (value is _DartActionRecord) return value.toRecord();\n");
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(o, " if (value is {n}) return value.toRecord();\n if (value is {n}CreateInput) return value.toCreateRecord();\n if (value is {n}Identity) return value.toRecord();").unwrap();
    }
    o.push_str(" return value;\n}\n");
    if !current.has_mutations() {
        o.push_str("class Mutations { Mutations(Client client); }\n");
    } else {
        o.push_str("/// Named Mutations use the same owned local scope on client and transaction.\nclass Mutations extends TransactionMutations { Mutations(super.port); }\n");
    }
    o.push_str("/// Query results are invocation snapshots.\nclass Queries {\n final Client client; Queries(this.client);\n");
    for (name, version, action) in current.iter() {
        if crate::action_names::kind(action) != axton_core::CallKind::Query {
            continue;
        }
        let params = dart_action_params(action);
        let store = dart_store_param(action);
        let controls = format!("bool {store} = true");
        let signature = if params.is_empty() {
            controls
        } else {
            format!("{params}, {controls}")
        };
        writeln!(o, " Future<{name}Output> {}({{{signature}}}) => this.client.invokeQuery<{name}Output>('{name}', {version}, {{{}}}, {}, store: {store});", lower(name), dart_action_arguments(action), dart_action_decoder(action, name)).unwrap();
    }
    o.push_str("}\n");
}
/// The Dart closure decoding an operation's `{name}Output` from its wire value.
pub(crate) fn dart_action_decoder(action: &Value, name: &str) -> String {
    let outputs = arr(action, "outputs");
    if outputs.is_empty() {
        return "(_) {}".to_string();
    }
    let fields = outputs
        .iter()
        .map(|field| {
            let key = s(field, "name");
            let value = format!("row['{key}']");
            format!("{key}: {}", dart_action_decode_field(field, &value))
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "(value) {{ final row = (value as Map).cast<String,dynamic>(); return {name}Output({fields}); }}"
    )
}
/// The business args map of a Dart operation call.
pub(crate) fn dart_action_arguments(action: &Value) -> String {
    arr(action, "inputs")
        .iter()
        .map(|arg| {
            let key = s(arg, "name");
            if arg["kind"] == "model" && arg["cardinality"] == "optional" {
                format!("if ({key} != null) '{key}': _dartActionEncode({key})")
            } else {
                format!("'{key}': _dartActionEncode({key})")
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}
pub(crate) fn dart_action_params(action: &Value) -> String {
    arr(action, "inputs")
        .iter()
        .map(|arg| {
            let optional = arg["kind"] == "model" && arg["cardinality"] == "optional";
            format!(
                "{}{} {}",
                if optional { "" } else { "required " },
                dart_action_input_type(
                    arg,
                    "",
                    s(action, "name"),
                    &Value::Null,
                    arg["allowedPatchFields"].is_array(),
                    true,
                ),
                s(arg, "name")
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

pub fn dart(v: &Value) -> String {
    let current = CurrentOperations::new(v);
    let mut o = String::from(
        "// Generated by axton. Do not edit.\nimport 'dart:async';\nimport 'dart:convert';\nimport 'package:axton/axton.dart';\nexport 'package:axton/axton.dart' show RuntimeConnection, SyncServer, AdmissionRefused, Call, CallOutcome, CallSuccess, CallFailure, CallStatus, CallError, StoreConnection, BootstrapStatus, BootstrapPhase, BootstrapError, BootstrapFailedException, ClientClosedException, PrerequisiteRetry, PrerequisiteHandler, AxtonDateTime, RefusedAct, FailedAct, FailedTask, SubmittedAct, ActOperation;\n",
    );
    o.push_str("class Present<T> { final T value; const Present(this.value); }\n");
    if !arr(v, "actions").is_empty() {
        o.push_str(
            "abstract interface class _DartActionRecord { Map<String,dynamic> toRecord(); }\n",
        );
    }
    writeln!(
        o,
        "final Map<String,dynamic> schema = jsonDecode({}) as Map<String,dynamic>;",
        dart_string(&v["schema"].to_string())
    )
    .unwrap();
    for en in arr(&v["schema"], "enums") {
        writeln!(
            o,
            "enum {} {{ {} }}",
            s(en, "name"),
            arr(en, "values")
                .iter()
                .map(|x| format!(
                    "{}{}",
                    dart_deprecated(
                        deprecation(
                            v,
                            "enumValue",
                            &[("enum", s(en, "name")), ("value", x.as_str().unwrap())]
                        ),
                        " "
                    ),
                    x.as_str().unwrap()
                ))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
    }
    if let Some(models) = v["abstractModels"].as_array() {
        for m in models {
            let n = s(m, "name");
            let parent = m["parent"]
                .as_str()
                .map(|p| format!(" implements {p}"))
                .unwrap_or_default();
            writeln!(o, "abstract interface class {n}{parent} {{").unwrap();
            for f in arr(m, "fields") {
                o.push_str(&dart_deprecated(
                    deprecation(v, "field", &[("model", n), ("field", s(f, "name"))]),
                    "\n",
                ));
                writeln!(o, " {} get {};", ft(f, true), s(f, "name")).unwrap();
            }
            o.push_str("}\n");
        }
    }
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        for suffix in ["", "Identity", "Patch"] {
            let fields: Vec<_> = arr(m, "fields")
                .iter()
                .filter(|f| {
                    let id = arr(m, "identity").contains(&f["name"]);
                    suffix.is_empty() || (suffix == "Identity" && id) || (suffix == "Patch" && !id)
                })
                .collect();
            let patch = suffix == "Patch";
            if suffix.is_empty() {
                writeln!(o, "/// What a fresh create of {n} accepts: a complete [{n}], or a [{n}Create] that may omit fields with creation defaults.\nabstract interface class {n}CreateInput {{ Map<String,dynamic> toCreateRecord(); }}").unwrap();
                let parent = v["inheritance"]
                    .as_array()
                    .and_then(|items| items.iter().find(|i| i["model"] == n))
                    .and_then(|i| i["parent"].as_str())
                    .map(|p| format!(", {p}"))
                    .unwrap_or_default();
                writeln!(o, "class {n} implements {n}CreateInput{parent} {{").unwrap();
            } else {
                writeln!(o, "class {n}{suffix} {{").unwrap();
            }
            for f in &fields {
                if let Some(reason) =
                    deprecation(v, "field", &[("model", n), ("field", s(f, "name"))])
                {
                    o.push(' ');
                    o.push_str(&dart_deprecated(Some(reason), "\n"));
                }
                writeln!(
                    o,
                    " final {} {};",
                    if patch {
                        format!("Present<{}>?", ft(f, true))
                    } else {
                        ft(f, true)
                    },
                    s(f, "name")
                )
                .unwrap();
            }
            writeln!(
                o,
                " const {n}{suffix}({});",
                if fields.is_empty() {
                    String::new()
                } else {
                    format!(
                        "{{{}}}",
                        fields
                            .iter()
                            .map(|f| format!(
                                "{}this.{}",
                                if patch { "" } else { "required " },
                                s(f, "name")
                            ))
                            .collect::<Vec<_>>()
                            .join(",")
                    )
                }
            )
            .unwrap();
            writeln!(o, " Map<String,dynamic> toRecord() => {{").unwrap();
            for f in &fields {
                let k = s(f, "name");
                let x = if patch {
                    format!("{k}!.value")
                } else {
                    k.into()
                };
                writeln!(
                    o,
                    " {}'{k}': {},",
                    if patch {
                        format!("if ({k} != null) ")
                    } else {
                        String::new()
                    },
                    enc(f, &x, true)
                )
                .unwrap();
            }
            o.push_str(" };\n");
            if !patch {
                writeln!(
                    o,
                    " factory {n}{suffix}.fromRecord(Map<String,dynamic> row) => {n}{suffix}("
                )
                .unwrap();
                for f in &fields {
                    let k = s(f, "name");
                    let x = format!("row['{k}']");
                    let d = decode(&f["type"], &x, true);
                    writeln!(
                        o,
                        " {k}: {},",
                        if f["nullable"] == true {
                            format!("{x} == null ? null : {d}")
                        } else {
                            d
                        }
                    )
                    .unwrap();
                }
                o.push_str(" );\n");
            }
            if suffix.is_empty() {
                o.push_str(" @override\n Map<String,dynamic> toCreateRecord() => toRecord();\n");
                writeln!(
                    o,
                    " {n}Identity get identity => {n}Identity({});",
                    arr(m, "identity")
                        .iter()
                        .map(|x| format!("{0}: {0}", x.as_str().unwrap()))
                        .collect::<Vec<_>>()
                        .join(",")
                )
                .unwrap();
            }
            o.push_str("}\n");
        }
    }
    for m in arr(&v["schema"], "models") {
        dart_create_class(v, m, &mut o);
    }

    dart_query_types(v, &mut o);
    dart_models(v, &mut o);
    dart_actions(v, &current, &mut o);
    dart_action_runtime(v, &current, &mut o);
    let names: Vec<(String, &str)> = arr(&v["schema"], "models")
        .iter()
        .map(|m| (lower(s(m, "name")), s(m, "name")))
        .collect();
    for (suffix, port) in [("Live", "Client"), ("Tx", "WritePort")] {
        writeln!(
            o,
            "class {suffix}Models {{ final {port} port; {suffix}Models(this.port);\n{}\n}}",
            names
                .iter()
                .map(|(key, n)| format!(
                    " late final {n}{suffix}Model {key} = {n}{suffix}Model(port);"
                ))
                .collect::<Vec<_>>()
                .join("\n")
        )
        .unwrap();
    }
    dart_fetch(v, &mut o);
    o.push_str("class GeneratedTransaction { final Transaction transaction; late final TxModels models=TxModels(transaction); GeneratedTransaction(this.transaction); }\n");
    crate::emit_transactions::dart_generated(&current, &mut o);
    o.push_str("class GeneratedClient {\n final Client client; RuntimeConnection? get connection => client.connection; late final LiveModels models=LiveModels(client);\n");
    if !arr(v, "actions").is_empty() {
        o.push_str(" late final Mutations mutations=Mutations(client);\n late final Queries queries=Queries(client);\n");
    }
    if has_models(v) {
        o.push_str(" late final FetchModels fetch=FetchModels(client);\n");
    }
    o.push_str(" GeneratedClient._(this.client);\n static Future<GeneratedClient> open({required String path, required String stream, StoreConnection? connection, String? libraryPath, Map<String,PrerequisiteHandler>? prerequisites}) async => GeneratedClient._(await Client.open(path:path,stream:stream,connection:connection,schema:schema,libraryPath:libraryPath,prerequisites:prerequisites));\n Future<void> bootstrap() => client.bootstrap();\n Future<RuntimeConnection> connect(SyncServer server,{void Function(Object)? onError,Future<void> Function()? refreshAuth,Duration directTimeout=const Duration(seconds:30)}) => client.connect(server,onError:onError,refreshAuth:refreshAuth,directTimeout:directTimeout);\n Future<void> resetStore({bool discardPending=false}) => client.resetStore(discardPending:discardPending);\n");
    let transaction = crate::emit_transactions::transaction_type(&current);
    writeln!(o, " Future<T> transaction<T>(Future<T> Function({transaction} tx) body) => client.transaction((tx) => body({transaction}(tx)));").unwrap();
    o.push_str(" /// This device's durable client identity.\n String get clientId => client.clientId;\n /// The client's sync state: a local snapshot, not a network probe.\n Future<Map<String,dynamic>> syncState() => client.syncState();\n /// Remove a handled rejection from the local inbox; it is not retried.\n Future<void> dismissRejection(int ordinal) => client.dismissRejection(ordinal);\n /// Remove unsent work and recompute local state; frozen work cannot be dropped.\n Future<void> drop(int ordinal) => client.drop(ordinal);\n Future<List<Map<String,dynamic>>> pendingTasks() => client.pendingTasks();\n /// Mark a prerequisite task by its opaque key: `ready`, `pending` or `failed`; `pending` runs its handler again at once.\n Future<void> setReadiness(String key, String state) => client.setReadiness(key, state);\n /// The refusals retained until dismissed, each with the act as submitted: `watch`, `get` and `dismiss`.\n late final rejections = client.rejections;\n /// The unsent acts blocked on a terminally failed prerequisite task: `watch`, `retry` and `drop`.\n late final failures = client.failures;\n /// The queue of unsettled acts: `watchPending`.\n late final outbound = client.outbound;\n /// Escape hatch: an untyped structured query.\n Future<List<Map<String,dynamic>>> querySpec(String model, Map<String,dynamic> query) => client.querySpec(model, query);\n /// Escape hatch: read-only SQL over the local database.\n Future<List<Map<String,dynamic>>> readSql(String sql, {List<dynamic> parameters = const []}) => client.readSql(sql, parameters: parameters);\n /// Read-only SQL over several Models: the current rows, then each different result after a commit that writes a table it reads.\n Stream<List<Map<String,dynamic>>> watchSql(String sql, {List<dynamic> parameters = const []}) => client.watchSql(sql, parameters: parameters);\n Future<void> close() => client.close();\n}\n");
    o
}
fn upper(name: &str) -> String {
    let mut chars = name.chars();
    format!("{}{}", chars.next().unwrap().to_uppercase(), chars.as_str())
}
fn ts_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let scalar = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let scalar = if scalar.is_empty() {
            "never".into()
        } else {
            scalar
        };
        let lists = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] == "list")
            .map(|f| format!("'{}'", s(f, "name")))
            .collect::<Vec<_>>()
            .join(" | ");
        let filter = if lists.is_empty() {
            format!("Partial<{n}>")
        } else {
            format!("Partial<Omit<{n}, {lists}>>")
        };
        writeln!(
            o,
            "export class {n}Model<P extends ReadPort=ReadPort> {{ readonly port:P; constructor(port:P) {{ this.port=port; }}"
        )
        .unwrap();
        writeln!(o, " async get(identity:{n}Identity):Promise<{n}|null> {{ const row=await this.port.read('{n}',encode{n}Identity(identity)); return row===null ? null : decode{n}(row); }}").unwrap();
        writeln!(o, " async query(options:{{where?:{filter};orderBy?:{{field:{scalar};direction:'ascending'|'descending'}}[];limit?:number}}={{}}):Promise<{n}[]> {{ return (await this.port.querySpec('{n}',{{filter:encode{n}Where(options.where??{{}}),orderBy:options.orderBy??[],...(options.limit===undefined?{{}}:{{limit:options.limit}})}})).map(decode{n}); }}").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const row=await this.port.related('{n}',encode{n}Identity(identity),'{name}'); return row===null?null:decode{target}(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}|null> {{ const rows=await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}');if(rows.length>1)throw Error('singular inverse has multiple rows');return rows.length===0?null:decode{target}(rows[0]!); }}").unwrap();
            } else {
                writeln!(o, " async {name}(identity:{n}Identity):Promise<{target}[]> {{ return (await this.port.referencing('{n}',encode{n}Identity(identity),'{target}','{reference}')).map(decode{target}); }}").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "export class {n}TxModel<P extends WritePort=WritePort> extends {n}Model<P> {{\n create(value:{n}Create):Promise<void> {{ return this.port.direct({{model:'{n}',op:'create',identity:encode{n}CreateIdentity(value),values:encode{n}Patch(value)}}); }}\n update(identity:{n}Identity, patch:{n}Patch):Promise<void> {{ return this.port.direct({{model:'{n}',op:'update',identity:encode{n}Identity(identity),values:encode{n}Patch(patch)}}); }}\n delete(identity:{n}Identity):Promise<void> {{ return this.port.direct({{model:'{n}',op:'delete',identity:encode{n}Identity(identity)}}); }}\n}}").unwrap();
        writeln!(o, "export class {n}LiveModel extends {n}TxModel<LivePort> {{\n watch(options:{{where?:{filter}}}, listener:(rows:{n}[])=>void, onError?:(error:unknown)=>void):()=>void {{ return this.port.watch('{n}',encode{n}Where(options.where??{{}}),(rows)=>listener(rows.map(decode{n})),onError); }}\n /** This record's sync state: its pending mutations and retained rejections. Local only. */\n async syncState(identity:{n}Identity):Promise<SyncState> {{ return (await this.port.syncState('{n}',encode{n}Identity(identity))) as SyncState; }}\n}}").unwrap();
    }
}
fn dart_query_types(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        let fields = arr(model, "fields")
            .iter()
            .filter(|f| f["type"]["kind"] != "list")
            .collect::<Vec<_>>();
        writeln!(o, "class {n}Filter {{").unwrap();
        for f in &fields {
            if let Some(reason) = deprecation(v, "field", &[("model", n), ("field", s(f, "name"))])
            {
                o.push(' ');
                o.push_str(&dart_deprecated(Some(reason), "\n"));
            }
            writeln!(o, " final Present<{}>? {};", ft(f, true), s(f, "name")).unwrap();
        }
        writeln!(
            o,
            " const {n}Filter({{{}}});\n Map<String,dynamic> toRecord()=>{{",
            fields
                .iter()
                .map(|f| format!("this.{}", s(f, "name")))
                .collect::<Vec<_>>()
                .join(",")
        )
        .unwrap();
        for f in &fields {
            let name = s(f, "name");
            writeln!(
                o,
                " if({name}!=null)'{name}':{},",
                enc(f, &format!("{name}!.value"), true)
            )
            .unwrap();
        }
        o.push_str("};\n}\n");
        let scalar = fields
            .iter()
            .filter(|f| f["type"]["kind"] == "scalar")
            .map(|f| format!("by{}('{}')", upper(s(f, "name")), s(f, "name")))
            .collect::<Vec<_>>()
            .join(",");
        writeln!(o,"enum {n}OrderField {{{scalar}; final String wireName; const {n}OrderField(this.wireName);}}\nclass {n}Order {{ final {n}OrderField field; final bool descending; const {n}Order(this.field,{{this.descending=false}}); Map<String,dynamic> toRecord()=>{{'field':field.wireName,'direction':descending?'descending':'ascending'}}; }}").unwrap();
    }
}
fn dart_models(v: &Value, o: &mut String) {
    for model in arr(&v["schema"], "models") {
        let n = s(model, "name");
        writeln!(
            o,
            "class {n}Model {{ final ReadPort port; {n}Model(this.port);"
        )
        .unwrap();
        writeln!(o, " Future<{n}?> get({n}Identity identity) async {{ final row=await port.read('{n}',identity.toRecord()); return row == null ? null : {n}.fromRecord(row); }}").unwrap();
        writeln!(o, " Future<List<{n}>> query({{{n}Filter? where,List<{n}Order> orderBy=const [],int? limit}}) async => (await port.querySpec('{n}',{{'filter':where?.toRecord()??{{}},'orderBy':orderBy.map((o)=>o.toRecord()).toList(),if(limit!=null)'limit':limit}})).map({n}.fromRecord).toList();").unwrap();
        for relation in arr(model, "relations") {
            let target = s(relation, "target");
            let name = s(relation, "name");
            writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{ final row=await port.related('{n}',identity.toRecord(),'{name}');return row==null?null:{target}.fromRecord(row); }}").unwrap();
        }
        for inverse in arr(v, "inverses").iter().filter(|i| i["model"] == n) {
            let target = s(inverse, "target");
            let name = s(inverse, "name");
            let reference = s(inverse, "reference");
            if inverse["list"] != true {
                writeln!(o, " Future<{target}?> {name}({n}Identity identity) async {{final rows=await port.referencing('{n}',identity.toRecord(),'{target}','{reference}');if(rows.length>1)throw StateError('singular inverse has multiple rows');return rows.isEmpty?null:{target}.fromRecord(rows.single);}}").unwrap();
            } else {
                writeln!(o, " Future<List<{target}>> {name}({n}Identity identity) async => (await port.referencing('{n}',identity.toRecord(),'{target}','{reference}')).map({target}.fromRecord).toList();").unwrap();
            }
        }
        o.push_str("}\n");
        writeln!(o, "class {n}LiveModel extends {n}TxModel {{ final Client client; {n}LiveModel(this.client) : super(client);\n Stream<List<{n}>> watch({{{n}Filter? where}}) => client.watch('{n}', where:where?.toRecord()??{{}}).map((rows) => rows.map({n}.fromRecord).toList());\n /// This record's sync state: its pending mutations and retained rejections. Local only.\n Future<SyncState> syncState({n}Identity identity) async => SyncState.fromRecord(await client.recordSyncState('{n}', identity.toRecord()));\n}}").unwrap();
        let split = dart_split_identity(model);
        writeln!(o, "class {n}TxModel extends {n}Model {{ final WritePort writer; {n}TxModel(this.writer) : super(writer);\n Future<void> create({n}CreateInput value) {{ final state=value.toCreateRecord(); {split} return writer.direct({{'model':'{n}','op':'create','identity':identity,'values':state}}); }}\n Future<void> update({n}Identity identity, {n}Patch patch) => writer.direct({{'model':'{n}','op':'update','identity':identity.toRecord(),'values':patch.toRecord()}});\n Future<void> delete({n}Identity identity) => writer.direct({{'model':'{n}','op':'delete','identity':identity.toRecord()}});\n}}").unwrap();
    }
}

/// A Dart single-quoted string literal whose value is exactly `text`: every
/// backslash, quote, dollar sign and control character is escaped, so no
/// schema content (such as a default string) can end or interpolate it.
fn dart_string(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('\'');
    for c in text.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => write!(out, "\\u{{{:x}}}", c as u32).unwrap(),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}
/// Statement moving a create record's identity fields out of `state` into
/// `identity`. An omitted (defaulted) identity field stays omitted.
fn dart_split_identity(model: &Value) -> String {
    let keys = arr(model, "identity")
        .iter()
        .map(|k| format!("'{}'", k.as_str().unwrap()))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "final identity=<String,dynamic>{{for (final key in const <String>[{keys}]) if (state.containsKey(key)) key: state.remove(key)}};"
    )
}
/// `{Model}Create`: the omission-preserving create input. A defaulted field
/// may be left out; a defaulted nullable field uses `Present` so an explicit
/// null stays distinct from omission. Other fields are as required as in
/// the full record.
fn dart_create_class(v: &Value, m: &Value, o: &mut String) {
    let n = s(m, "name");
    let fields = arr(m, "fields");
    writeln!(o, "class {n}Create implements {n}CreateInput {{").unwrap();
    for f in fields {
        if let Some(reason) = deprecation(v, "field", &[("model", n), ("field", s(f, "name"))]) {
            o.push(' ');
            o.push_str(&dart_deprecated(Some(reason), "\n"));
        }
        let ty = match (defaulted(f), f["nullable"] == true) {
            (true, true) => format!("Present<{}>?", ft(f, true)),
            (true, false) => format!("{}?", ft(f, true)),
            (false, _) => ft(f, true),
        };
        writeln!(o, " final {ty} {};", s(f, "name")).unwrap();
    }
    writeln!(
        o,
        " const {n}Create({{{}}});",
        fields
            .iter()
            .map(|f| format!(
                "{}this.{}",
                if defaulted(f) { "" } else { "required " },
                s(f, "name")
            ))
            .collect::<Vec<_>>()
            .join(",")
    )
    .unwrap();
    o.push_str(" @override\n Map<String,dynamic> toCreateRecord() => {\n");
    for f in fields {
        let k = s(f, "name");
        let line = match (defaulted(f), f["nullable"] == true) {
            (true, true) => format!(
                " if ({k} != null) '{k}': {},",
                enc(f, &format!("{k}!.value"), true)
            ),
            (true, false) => format!(
                " if ({k} != null) '{k}': {},",
                encoded(&f["type"], &format!("{k}!"), true)
            ),
            (false, _) => format!(" '{k}': {},", enc(f, k, true)),
        };
        writeln!(o, "{line}").unwrap();
    }
    o.push_str(" };\n}\n");
}

// Model Fetch ([#153](https://github.com/zanminwang/axton/issues/153)): one
// method per Model that reads its complete snapshot through the existing
// Loader at the Model's local read version. The SDK's raw `fetchModel` submits
// the Rust task; these only encode the identity and decode each caller's own
// result with the Model's codecs. Nothing is emitted for a schema without
// Models, and nothing reaches the transaction facades.
fn has_models(v: &Value) -> bool {
    !arr(&v["schema"], "models").is_empty()
}
fn ts_fetch(v: &Value, o: &mut String) {
    if !has_models(v) {
        return;
    }
    let models = arr(&v["schema"], "models");
    o.push_str("export interface FetchPort { fetchModel<T>(model:string,version:number,identity:object,decode:(row:Record<string,unknown>)=>T,options?:{store?:boolean}):Promise<T|null>; }\n");
    o.push_str("/** One-shot remote reads: the complete snapshot through the Model's Loader, or null. `store: false` skips local cache writes. */\nexport interface FetchModels {\n");
    for m in models {
        let n = s(m, "name");
        writeln!(
            o,
            " {}(identity:{n}Identity, options?:{{store?:boolean}}):Promise<{n}|null>;",
            lower(n)
        )
        .unwrap();
    }
    o.push_str("}\nexport function fetchModels(port:FetchPort):FetchModels { return {\n");
    for m in models {
        let n = s(m, "name");
        writeln!(
            o,
            " {}:(identity,options)=>port.fetchModel('{n}',{},encode{n}Identity(identity),decode{n},options),",
            lower(n),
            m["version"]
        )
        .unwrap();
    }
    o.push_str("}; }\n");
}
fn dart_fetch(v: &Value, o: &mut String) {
    if !has_models(v) {
        return;
    }
    o.push_str("/// One-shot remote reads: the complete snapshot through the Model's Loader, or null. `store: false` skips local cache writes.\nclass FetchModels { final Client _client; FetchModels(this._client);\n");
    for m in arr(&v["schema"], "models") {
        let n = s(m, "name");
        writeln!(
            o,
            " Future<{n}?> {}({n}Identity identity, {{bool store = true}}) => _client.fetchModel('{n}', {}, identity.toRecord(), {n}.fromRecord, store: store);",
            lower(n),
            m["version"]
        )
        .unwrap();
    }
    o.push_str("}\n");
}
