//! Generated Load surfaces ([#173](https://github.com/zanminwang/axton/issues/173)):
//! the backend `Loads<Tx>` handler contracts and the client `loads` facades in
//! TypeScript and Dart. Every function here emits nothing for a schema without
//! Loads, so such a schema keeps its generated bytes; the names emitted beside
//! a Load are the ones [`crate::action_names`] reserves.
use crate::emit::{
    action_input_type, action_type_name, arr, backend_action_output_type, dart_action_input_type,
    dart_option_params, encoded, historical_action_input_type, lower, s, ts_action_encode_input,
};
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::fmt::Write;

/// Whether the configuration declares (or retains) a Load.
pub(crate) fn has_loads(v: &Value) -> bool {
    v["loads"].as_array().is_some_and(|loads| !loads.is_empty())
}
/// The newest version of each Load name.
fn latest(v: &Value) -> BTreeMap<&str, u64> {
    let mut latest = BTreeMap::new();
    for load in v["loads"].as_array().into_iter().flatten() {
        let version = load["version"].as_u64().unwrap();
        latest
            .entry(s(load, "name"))
            .and_modify(|v: &mut u64| *v = (*v).max(version))
            .or_insert(version);
    }
    latest
}
/// The descriptor a client starts: the newest version of each name, by name.
fn current(v: &Value) -> Vec<&Value> {
    latest(v)
        .into_iter()
        .map(|(name, version)| {
            arr(v, "loads")
                .iter()
                .find(|l| s(l, "name") == name && l["version"].as_u64() == Some(version))
                .unwrap()
        })
        .collect()
}

// --- TypeScript client --------------------------------------------------------

/// `generated.ts` reads the handle types the client module re-exports.
pub(crate) fn ts_generated_imports(v: &Value, o: &mut String) {
    if has_loads(v) {
        o.push_str("import type { Load, LoadOptions, LoadStatus } from './client.ts';\n");
    }
}
/// Each current Load's `{Name}Input`, its encoder and `makeLoads`: a start
/// method per Load under its lower-first name, `get`, `list` and
/// `invalidate.<name>`. Options stay apart from business args.
pub(crate) fn ts_generated(v: &Value, o: &mut String) {
    let loads = current(v);
    if loads.is_empty() {
        return;
    }
    for load in &loads {
        let name = s(load, "name");
        writeln!(o, "export interface {name}Input {{").unwrap();
        for arg in arr(load, "inputs") {
            writeln!(o, " {}: {};", s(arg, "name"), action_input_type(arg, false)).unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "function encode{name}Input(args:{name}Input):Record<string,unknown> {{ return {{"
        )
        .unwrap();
        for arg in arr(load, "inputs") {
            let key = s(arg, "name");
            let expr = ts_action_encode_input(arg, &format!("args.{key}"));
            writeln!(o, " {key}: {expr},").unwrap();
        }
        o.push_str("}; }\n");
    }
    o.push_str("/** Loads resolve after durable local acceptance with a `Load` handle and need no connection; `once` reuses the job an earlier once start registered, `invalidate` removes that registration offline, `get` reattaches by ID and `list` shows the most recent jobs. */\nexport function makeLoads(port:{ startLoad<Name extends string>(name:Name,version:number,args:object,options?:LoadOptions):Promise<Load<Name>>; getLoad(id:string):Promise<Load|null>; listLoads(options?:{limit?:number}):Promise<LoadStatus[]>; invalidateLoad(name:string,args:object):Promise<void>; }) { return {\n");
    for load in &loads {
        let name = s(load, "name");
        writeln!(o, " {}: (args:{name}Input, options?:LoadOptions):Promise<Load<'{name}'>> => port.startLoad('{name}',{},encode{name}Input(args),options),", lower(name), load["version"]).unwrap();
    }
    o.push_str(" get: (id:string):Promise<Load|null> => port.getLoad(id),\n list: (options?:{limit?:number}):Promise<LoadStatus[]> => port.listLoads(options),\n invalidate: {\n");
    for load in &loads {
        let name = s(load, "name");
        writeln!(o, "  {}: (args:{name}Input):Promise<void> => port.invalidateLoad('{name}',encode{name}Input(args)),", lower(name)).unwrap();
    }
    o.push_str(" }\n}; }\n");
}
/// `client.ts` re-exports the handle types and imports the facade.
pub(crate) fn ts_client_imports(v: &Value, runtime: &str, o: &mut String) {
    if has_loads(v) {
        writeln!(o, "export {{ LoadError, type Load, type LoadOptions, type LoadPhase, type LoadStatus }} from \"{runtime}\";").unwrap();
        o.push_str("import { makeLoads } from \"./generated.ts\";\n");
    }
}

// --- Dart client --------------------------------------------------------------

/// The handle types the generated library re-exports beside a Load.
pub(crate) fn dart_exports(v: &Value, o: &mut String) {
    if has_loads(v) {
        o.push_str(
            "export 'package:axton/axton.dart' show Load, LoadStatus, LoadPhase, LoadException;\n",
        );
    }
}
/// One Dart business input as the wire encodes it.
fn dart_encode_input(input: &Value, x: &str) -> String {
    let ty = if input["list"] == true {
        json!({"kind":"list","element":input["type"]})
    } else {
        input["type"].clone()
    };
    let mut expr = encoded(&ty, x, true);
    // A list whose elements encode as themselves is sent as it is.
    if expr == format!("{x}.map((e) => e).toList()") {
        expr = x.to_string();
    }
    if input["nullable"] == true && expr != x {
        format!("{x} == null ? null : {expr}")
    } else {
        expr
    }
}
/// The route field as a Load method body names it: `this.client` when a
/// business input named `client` shadows the field, `client` otherwise (so
/// no `unnecessary_this` lint fires on ordinary Loads).
fn dart_route(load: &Value) -> &'static str {
    if arr(load, "inputs")
        .iter()
        .any(|arg| s(arg, "name") == "client")
    {
        "this.client"
    } else {
        "client"
    }
}
/// The named business parameters and their args map of one Load.
fn dart_business(load: &Value) -> (Vec<String>, String) {
    let params = arr(load, "inputs")
        .iter()
        .map(|arg| {
            format!(
                "required {} {}",
                dart_action_input_type(arg, "", s(load, "name"), &Value::Null, false, true),
                s(arg, "name")
            )
        })
        .collect();
    let args = arr(load, "inputs")
        .iter()
        .map(|arg| {
            let key = s(arg, "name");
            format!("'{key}': {}", dart_encode_input(arg, key))
        })
        .collect::<Vec<_>>()
        .join(", ");
    (params, args)
}
/// `Loads` (a start method per Load, `get`, `list`, `invalidate`) and
/// `LoadInvalidations`. The `once` and `refresh` controls are named
/// parameters, `callOnce`/`callRefresh` when a business input takes the name.
pub(crate) fn dart_client(v: &Value, o: &mut String) {
    let loads = current(v);
    if loads.is_empty() {
        return;
    }
    o.push_str("/// Loads resolve after durable local acceptance with a [Load] handle and need no connection; `once` reuses the job an earlier once start registered, [invalidate] removes that registration offline, [get] reattaches by ID and [list] shows the most recent jobs.\nclass Loads {\n final Client client; Loads(this.client);\n late final LoadInvalidations invalidate = LoadInvalidations(client);\n");
    for load in &loads {
        let name = s(load, "name");
        let (mut params, args) = dart_business(load);
        let taken = arr(load, "inputs")
            .iter()
            .map(|arg| s(arg, "name").to_string())
            .collect();
        let (once, refresh) = dart_option_params(taken);
        params.push(format!("bool {once} = false"));
        params.push(format!("bool {refresh} = false"));
        writeln!(o, " Future<Load> {}({{{}}}) => {}.startLoad('{name}', {}, {{{args}}}, once: {once}, refresh: {refresh});", lower(name), params.join(", "), dart_route(load), load["version"]).unwrap();
    }
    o.push_str(" Future<Load?> get(String id) => client.getLoad(id);\n Future<List<LoadStatus>> list({int limit = 50}) => client.listLoads(limit: limit);\n}\n");
    o.push_str("/// Removes the once registrations of one Load argument set across its retained versions, offline; no job is cancelled and no Model deleted.\nclass LoadInvalidations {\n final Client client; LoadInvalidations(this.client);\n");
    for load in &loads {
        let name = s(load, "name");
        let (params, args) = dart_business(load);
        let signature = if params.is_empty() {
            String::new()
        } else {
            format!("{{{}}}", params.join(", "))
        };
        writeln!(
            o,
            " Future<void> {}({signature}) => {}.invalidateLoad('{name}', {{{args}}});",
            lower(name),
            dart_route(load)
        )
        .unwrap();
    }
    o.push_str("}\n");
}

// --- TypeScript backend -------------------------------------------------------

/// The backend handler contracts: portable JSON state, `LoadNext`, the
/// `LoadContext` whose only effect is tracking through `LoadStream`, and per
/// retained version `{Name}Input` and `{Name}HandlerOutput` (`V{n}`-prefixed
/// when retained), grouped in `Loads<Tx>` like `Queries<Tx>`.
pub(crate) fn backend(v: &Value, models: &[Value], o: &mut String) {
    let loads = arr(v, "loads");
    o.push_str("/** Portable JSON: no undefined, functions, cycles, non-finite numbers, BigInt or class instances. Encode integers outside the safe range and dates as strings. */\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n");
    o.push_str("/** A page's `continuation` is `null` on the first page, and answering `next: null` completes the Load; `{ state }` continues it, and `{ state: null }` is a legitimate state. At most 64 KiB encoded and 64 levels deep. */\nexport type LoadNext = null | { state: JsonValue };\n");
    o.push_str("/** A Load page's context: it has no `invalidate`, and its `stream` only tracks. `callId` is the page's durable call ID and `loadId` its job. */\nexport interface LoadContext<Tx> {\n tx: Tx;\n userId: string;\n callId: string;\n loadId: string;\n stream(names: string | readonly string[]): LoadStream;\n}\n");
    o.push_str("/** One page request: `continuation` is `null` first and the previous non-null `next` afterwards. */\nexport type LoadHandlerCall<Tx, Args> = { ctx: LoadContext<Tx>; args: Args; continuation: LoadNext };\n");
    let latest = latest(v);
    for load in loads {
        let latest = latest[s(load, "name")];
        writeln!(
            o,
            "export interface {} {{",
            action_type_name(load, latest, "Input")
        )
        .unwrap();
        for arg in arr(load, "inputs") {
            writeln!(
                o,
                " {}: {};",
                s(arg, "name"),
                historical_action_input_type(arg, load, latest)
            )
            .unwrap();
        }
        o.push_str("}\n");
        writeln!(
            o,
            "export interface {} {{\n data: {{",
            action_type_name(load, latest, "HandlerOutput")
        )
        .unwrap();
        for output in arr(load, "outputs") {
            writeln!(
                o,
                "  {}: {};",
                s(output, "name"),
                backend_action_output_type(output, load, models)
            )
            .unwrap();
        }
        o.push_str(" };\n next: LoadNext;\n}\n");
    }
    // A bare function is shorthand only for a v1-only Load.
    o.push_str("export interface Loads<Tx> {\n");
    for (name, &newest) in &latest {
        let mut versions: Vec<&Value> = loads.iter().filter(|l| s(l, "name") == *name).collect();
        versions.sort_by_key(|l| l["version"].as_u64().unwrap());
        let signature = |load: &Value| {
            (
                action_type_name(load, newest, "Input"),
                action_type_name(load, newest, "HandlerOutput"),
            )
        };
        let members = versions
            .iter()
            .map(|l| {
                let (input, output) = signature(l);
                format!(
                    "v{}(call: LoadHandlerCall<Tx, {input}>): Promise<{output}>",
                    l["version"].as_u64().unwrap()
                )
            })
            .collect::<Vec<_>>()
            .join("; ");
        if versions.len() == 1 && versions[0]["version"].as_u64() == Some(1) {
            let (input, output) = signature(versions[0]);
            writeln!(o, " {}: {{ {members} }} | ((call: LoadHandlerCall<Tx, {input}>) => Promise<{output}>);", lower(name)).unwrap();
        } else {
            writeln!(o, " {}: {{ {members} }};", lower(name)).unwrap();
        }
    }
    o.push_str("}\n");
}
