//! Generated transaction surfaces for transactional Mutation enqueue: the
//! application transaction queues typed Mutations under `mutations`, each
//! with an optional `local` callback whose context has Models only, while the
//! onStore transaction keeps its local Model and Channel surface. Every
//! function here emits nothing for a schema without a current Mutation, so
//! such a schema keeps its generated bytes; the names emitted beside a
//! Mutation are the ones [`crate::action_names`] reserves.
use crate::emit::{
    arr, dart_action_arguments, dart_action_decoder, dart_action_params, dart_store_param,
    dart_unique_param, lower, s,
};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fmt::Write;

/// Each current Mutation, by name, with its latest version: an operation
/// whose latest version is a Query is not queued in a transaction.
pub(crate) fn current_mutations(v: &Value) -> Vec<(&str, u64, &Value)> {
    let actions = arr(v, "actions");
    let mut latest = BTreeMap::new();
    for action in actions {
        let version = action["version"].as_u64().unwrap();
        latest
            .entry(s(action, "name"))
            .and_modify(|v: &mut u64| *v = (*v).max(version))
            .or_insert(version);
    }
    latest
        .into_iter()
        .filter_map(|(name, version)| {
            let action = actions
                .iter()
                .find(|a| s(a, "name") == name && a["version"].as_u64() == Some(version))?;
            (crate::action_names::kind(action) == axton_core::CallKind::Mutation)
                .then_some((name, version, action))
        })
        .collect()
}

/// The facade `client.transaction` passes to its callback: the application
/// transaction beside a current Mutation, otherwise the local-only one.
pub(crate) fn transaction_type(v: &Value) -> &'static str {
    if current_mutations(v).is_empty() {
        "GeneratedTransaction"
    } else {
        "ApplicationTransaction"
    }
}

/// The raw submission port, the companion context, `makeTransactionMutations`
/// and `ApplicationTransaction`. The port's `local` callback receives the
/// runtime's restricted companion port; each method wraps the application's
/// callback so it receives the typed [`CompanionContext`] instead.
pub(crate) fn ts_generated(v: &Value, o: &mut String) {
    let mutations = current_mutations(v);
    if mutations.is_empty() {
        return;
    }
    o.push_str("/** The raw options of a Mutation queued in an application transaction: store policy and the `local` callback, which receives the restricted companion port. */\nexport type SubmitMutationOptions = CallOptions & { local?: (port:WritePort) => Promise<void> };\n");
    o.push_str("export interface SubmitMutationPort { submitMutation<T>(name:string,version:number,args:object,decode:(value:unknown)=>T,options?:SubmitMutationOptions):Promise<Call<T>>; }\n/** The raw application transaction's resolutions of unsent work, which only `ApplicationTransaction` needs. */\nexport interface UnsentResolutionPort { readonly rejections:{ dismiss(id:number):Promise<void> }; readonly failures:{ retry(taskKeys:string[]):Promise<void>; drop(ordinal:number):Promise<void> }; }\n");
    o.push_str("/** A Mutation's `local` callback context: typed local Model reads and writes, recorded as that Mutation's companions. It queues no Mutation and has no Channels, watch or savepoints. */\nexport class CompanionContext { readonly models:TxModels; constructor(port:WritePort) { this.models=txModels(port); } }\n");
    o.push_str("/** Transaction-only option: `local` runs inside the open transaction and its Model writes belong to that Mutation. */\nexport type CompanionOptions = { local?: (local:CompanionContext) => Promise<void> };\n");
    o.push_str("/** Mutations queued in an application transaction: each resolves with its `Call` after its optimism and `local` callback ran; the Call is sendable only after the local commit. There is no `call` route. */\nexport function makeTransactionMutations(port:SubmitMutationPort) { const submit=(options:(CallOptions & CompanionOptions)|undefined):SubmitMutationOptions|undefined => { if (options===undefined) return undefined; const {local,...rest}=options; return local===undefined ? rest : {...rest,local:(companion:WritePort)=>local(new CompanionContext(companion))}; }; return {\n");
    for (name, version, _) in &mutations {
        writeln!(o, " {}: (args:{name}Input, options?:{name}Options & CompanionOptions):Promise<Call<{name}Output>> => port.submitMutation('{name}',{version},encode{name}Input(args),decode{name}Output,submit(options)),", lower(name)).unwrap();
    }
    o.push_str("}; }\n");
    o.push_str("/** The application transaction: local Models and Channels, `mutations`, which queue typed Mutations in the same local commit, and `rejections` / `failures`, which resolve unsent work in it: each takes effect for the rest of the callback and commits or rolls back with it. */\nexport class ApplicationTransaction extends GeneratedTransaction { readonly mutations:ReturnType<typeof makeTransactionMutations>; readonly rejections:UnsentResolutionPort['rejections']; readonly failures:UnsentResolutionPort['failures']; constructor(transaction:WritePort & SubmitMutationPort & UnsentResolutionPort) { super(transaction); this.mutations=makeTransactionMutations(transaction); this.rejections=transaction.rejections; this.failures=transaction.failures; } }\n");
}

/// The Dart twin of [`ts_generated`]. `SubmitMutationPort` is the runtime's
/// (`package:axton`), which the raw `Transaction` implements.
pub(crate) fn dart_generated(v: &Value, o: &mut String) {
    let mutations = current_mutations(v);
    if mutations.is_empty() {
        return;
    }
    o.push_str("/// A Mutation's `local` callback context: typed local Model reads and writes, recorded as that Mutation's companions. It queues no Mutation and has no Channels, watch or savepoints.\nclass CompanionContext { final TxModels models; CompanionContext(WritePort port) : models = TxModels(port); }\n");
    o.push_str("/// Mutations queued in an application transaction: each returns its [Call] after its optimism and `local` callback ran; the Call is sendable only after the local commit. There is no `call` route.\nclass TransactionMutations {\n final SubmitMutationPort _port; TransactionMutations(this._port);\n");
    for (name, version, action) in &mutations {
        let params = dart_action_params(action);
        let store = dart_store_param(action);
        let mut taken: Vec<String> = arr(action, "inputs")
            .iter()
            .map(|input| s(input, "name").to_string())
            .collect();
        taken.push(store.clone());
        let local = dart_unique_param(&mut taken, "local", "callLocal");
        let controls =
            format!("{name}Store? {store}, Future<void> Function(CompanionContext local)? {local}");
        let signature = if params.is_empty() {
            controls
        } else {
            format!("{params}, {controls}")
        };
        writeln!(
            o,
            " Future<Call<{name}Output>> {}({{{signature}}}) => _port.submitMutation<{name}Output>('{name}', {version}, {{{}}}, {}, store: {store}, local: {local} == null ? null : (port) => {local}(CompanionContext(port)));",
            lower(name),
            dart_action_arguments(action),
            dart_action_decoder(action, name),
        )
        .unwrap();
    }
    o.push_str("}\n");
    o.push_str("/// The application transaction: local Models and Channels, [mutations], which queue typed Mutations in the same local commit, and [rejections] / [failures], which resolve unsent work in it: each takes effect for the rest of the callback and commits or rolls back with it.\nclass ApplicationTransaction extends GeneratedTransaction { late final TransactionMutations mutations = TransactionMutations(transaction); late final rejections = transaction.rejections; late final failures = transaction.failures; ApplicationTransaction(super.transaction); }\n");
}
