// Runs inside a scratch project that installed the packed packages: every
// import below is a package specifier or a file generated by the installed CLI.
import test from "node:test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Pool } from "pg";
import { pg, type PgClient } from "@axtonjs/postgres/pg";
import {
  createBackend,
  devAuth,
  type Loaders,
  type Mutations,
} from "./generated/backend.ts";
import { GeneratedClient } from "./generated/client.ts";

const settled = async (client: GeneratedClient): Promise<void> => {
  for (let attempt = 0; attempt < 500; attempt++) {
    if ((await client.syncState()).pending === 0) return;
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  throw new Error("the pending mutation did not reach the backend");
};

test("installed client and backend: local writes survive reopening, then sync", async () => {
  const databaseUrl = process.env.DATABASE_URL;
  assert.ok(
    databaseUrl,
    "DATABASE_URL names the disposable PostgreSQL cluster",
  );
  const directory = await mkdtemp(join(tmpdir(), "axton-installed-client-"));
  const path = join(directory, "client.sqlite");
  const pool = new Pool({ connectionString: databaseUrl });
  let server: { url: string; close(): Promise<void> } | undefined;
  let client: GeneratedClient | undefined;
  try {
    // Offline: open a local database, write, close and reopen it.
    client = await GeneratedClient.open({
      path,
      stream: "User:installed",
      connection: {
        url: "http://127.0.0.1:1",
        token: "installed",
      },
    });
    await client.mutations.addNote({
      note: { id: "note-1", text: "written offline" },
    });
    assert.equal(
      (await client.models.note.get({ id: "note-1" }))?.text,
      "written offline",
    );
    await client.close();
    client = await GeneratedClient.open({
      path,
      stream: "User:installed",
      connection: {
        url: "http://127.0.0.1:1",
        token: "installed",
      },
    });
    assert.equal(
      (await client.models.note.get({ id: "note-1" }))?.text,
      "written offline",
    );
    assert.equal(
      (await client.syncState()).pending,
      1,
      "the write is kept as unsent work",
    );
    await client.close();
    client = undefined;

    // The backend: framework tables from the installed migration, one application table.
    const migration = await readFile(
      createRequire(import.meta.url).resolve("@axtonjs/postgres/migration.sql"),
      "utf8",
    );
    await pool.query(migration); // one simple-protocol call: the file holds dollar-quoted functions
    await pool.query(
      "CREATE TABLE note (id text PRIMARY KEY, text text NOT NULL)",
    );
    const mutations: Mutations<PgClient> = {
      async addNote({ args, ctx }) {
        await ctx.tx.query("INSERT INTO note (id, text) VALUES ($1, $2)", [
          args.note.id,
          args.note.text.trim(),
        ]);
        ctx.stream.track.note({ id: args.note.id });
      },
    };
    const loaders: Loaders<PgClient> = {
      async note({ ids, tx }) {
        const { rows } = await tx.query(
          "SELECT id, text FROM note WHERE id = ANY($1)",
          [ids.map((identity) => identity.id)],
        );
        const byId = new Map(
          rows.map((row) => [
            row.id,
            { id: String(row.id), text: String(row.text) },
          ]),
        );
        return ids.map((identity) => byId.get(identity.id) ?? null);
      },
    };
    const backend = createBackend<PgClient>({
      database: pg(pool),
      authenticate: devAuth(),
      protocol5: {
        authorizeStream: (viewer, stream) => stream === `User:${viewer}`,
      },
      queries: {},
      mutations,
      loaders,
      bootstrap: async () => {},
    });
    server = await backend.listen({ port: 0 });

    // Online: the unsent write reaches the backend, and a named durable Call returns its settled outcome.
    client = await GeneratedClient.open({
      path,
      stream: "User:installed",
      connection: {
        url: server.url,
        token: "installed",
      },
    });
    await settled(client);
    assert.deepEqual(
      (await pool.query("SELECT text FROM note WHERE id = 'note-1'")).rows,
      [{ text: "written offline" }],
    );
    const call = await client.mutations.addNote({
      note: { id: "note-2", text: "durable" },
    });
    const outcome = await call.wait();
    assert.equal(outcome.error, null);
    assert.deepEqual(
      (await pool.query("SELECT text FROM note WHERE id = 'note-2'")).rows,
      [{ text: "durable" }],
    );
    // Untracked business rows remain invocation snapshots until explicitly stored.
    await pool.query(
      "INSERT INTO note (id, text) VALUES ('snapshot-only', 'fresh snapshot'), ('dart-snapshot', 'Dart snapshot')",
    );
    assert.equal(
      (await client.fetch.note({ id: "snapshot-only" }, { store: false }))?.text,
      "fresh snapshot",
    );
    assert.equal(await client.models.note.get({ id: "snapshot-only" }), null);
    assert.equal(
      (await client.fetch.note({ id: "snapshot-only" }, { store: true }))?.text,
      "fresh snapshot",
    );
    assert.equal(
      (await client.models.note.get({ id: "snapshot-only" }))?.text,
      "fresh snapshot",
    );
    if (process.env.AXTON_STAGED_DART) {
      assert.ok(
        process.env.AXTON_VERIFY_DART,
        "the package harness supplies its Dart runner",
      );
      const dart = await promisify(execFile)(
        "bash",
        [
          process.env.AXTON_VERIFY_DART,
          process.env.AXTON_STAGED_DART,
          server.url,
          join(process.cwd(), "generated/generated.dart"),
        ],
        { timeout: 90000, maxBuffer: 1024 * 1024 },
      );
      assert.match(dart.stdout, /installed generated Dart real backend: PASS/);
      console.log("installed generated Dart real backend: PASS");
    }
  } finally {
    await client?.close();
    await server?.close();
    await pool.end();
    await rm(directory, { recursive: true, force: true });
  }
});
